-- 对话配置文件
-- Generated by doc_to_lua.py (Phase 2 — do not overwrite production files)
-- Scene DialogueTrigger start ID should be 0 (entry dispatcher)
-- doc node map:
--   2-A -> DialogueConfig[1]
--   2-hub -> DialogueConfig[23]
--   2-B -> DialogueConfig[24]
--   2-C -> DialogueConfig[45]
--   2-D -> DialogueConfig[51]
--   2-F -> DialogueConfig[60]
--   2-E -> DialogueConfig[74]
--   2-G -> DialogueConfig[200]
--   3-A -> DialogueConfig[130]
--   entry#2g -> DialogueConfig[190]
--   NGPlus -> DialogueConfig[131]
--   NGPlus-revisit -> DialogueConfig[172]

--   __entry__ -> DialogueConfig[0]
--   __entry__ -> DialogueConfig[0]
--   2-hub#s1#menu -> DialogueConfig[173]
--   2-hub#s2#menu -> DialogueConfig[174]
--   2-hub#s3#menu -> DialogueConfig[175]
--   2-hub#return#menu -> DialogueConfig[177]
--   entry#hub -> DialogueConfig[183]
--   entry#3a1 -> DialogueConfig[184]
--   entry#3a2 -> DialogueConfig[185]
--   entry#3a0 -> DialogueConfig[186]
--   entry#2a -> DialogueConfig[187]
--   entry#ng1 -> DialogueConfig[188]
--   entry#ng2 -> DialogueConfig[189]
DialogueConfig = {}

-- 普通对话类型  -- doc:2-A#1
-- Position: { 3450, 150 }
DialogueConfig[1] = {
    Type = "Normal",
    DocTag = "2-A#1",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "嘿，你们在干什么？",
    Next = 2  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#2
-- Position: { 3800, 150 }
DialogueConfig[2] = {
    Type = "Normal",
    DocTag = "2-A#2",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（四只小鸡挤在鸡舍边，各自戴着歪歪扭扭的纸板墨镜装酷）",
    Next = 3  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#3
-- Position: { 4150, 150 }
DialogueConfig[3] = {
    Type = "Normal",
    DocTag = "2-A#3",
    NpcName = "米粒",
    NpcSprite = "装酷",
    Dialogue = "（小声）有人来了……",
    Next = 4  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#4
-- Position: { 4500, 150 }
DialogueConfig[4] = {
    Type = "Normal",
    DocTag = "2-A#4",
    NpcName = "豆豆",
    NpcSprite = "装酷",
    Dialogue = "别、别看他……",
    Next = 5  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#5
-- Position: { 4850, 150 }
DialogueConfig[5] = {
    Type = "Normal",
    DocTag = "2-A#5",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（阿满往前挪了半步，又停住）",
    Next = 6  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#6
-- Position: { 5200, 150 }
DialogueConfig[6] = {
    Type = "Normal",
    DocTag = "2-A#6",
    NpcName = "阿满",
    NpcSprite = "装酷",
    Dialogue = "……",
    Next = 7  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#7
-- Position: { 5550, 150 }
DialogueConfig[7] = {
    Type = "Normal",
    DocTag = "2-A#7",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "淑芬的蛋不见了，你们知道吗？",
    Next = 8  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#8
-- Position: { 5900, 150 }
DialogueConfig[8] = {
    Type = "Normal",
    DocTag = "2-A#8",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（阿满墨镜滑到喙尖）",
    Next = 9  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#9
-- Position: { 6250, 150 }
DialogueConfig[9] = {
    Type = "Normal",
    DocTag = "2-A#9",
    NpcName = "瓜子",
    NpcSprite = "装酷",
    Dialogue = "（极小声）弟弟……",
    Next = 10  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#10
-- Position: { 6600, 150 }
DialogueConfig[10] = {
    Type = "Normal",
    DocTag = "2-A#10",
    NpcName = "阿满",
    NpcSprite = "心虚",
    Dialogue = "（急）瓜子！别乱叫！",
    Next = 11  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#11
-- Position: { 6950, 150 }
DialogueConfig[11] = {
    Type = "Normal",
    DocTag = "2-A#11",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（阿满把墨镜顶回去）",
    Next = 12  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#12
-- Position: { 7300, 150 }
DialogueConfig[12] = {
    Type = "Normal",
    DocTag = "2-A#12",
    NpcName = "阿满",
    NpcSprite = "装酷",
    Dialogue = "我们……暗影侦探团……也在查这案子。",
    Next = 13  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#13
-- Position: { 7650, 150 }
DialogueConfig[13] = {
    Type = "Normal",
    DocTag = "2-A#13",
    NpcName = "阿满",
    NpcSprite = "装酷",
    Dialogue = "事情不小。你最好别乱插手。",
    Next = 14  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#14
-- Position: { 8000, 150 }
DialogueConfig[14] = {
    Type = "Normal",
    DocTag = "2-A#14",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "能告诉我点什么吗？",
    Next = 15  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#15
-- Position: { 8350, 150 }
DialogueConfig[15] = {
    Type = "Normal",
    DocTag = "2-A#15",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（豆豆拽了拽阿满翅膀）",
    Next = 16  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#16
-- Position: { 8700, 150 }
DialogueConfig[16] = {
    Type = "Normal",
    DocTag = "2-A#16",
    NpcName = "阿满",
    NpcSprite = "装酷",
    Dialogue = "……",
    Next = 17  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#17
-- Position: { 9050, 150 }
DialogueConfig[17] = {
    Type = "Normal",
    DocTag = "2-A#17",
    NpcName = "阿满",
    NpcSprite = "装酷",
    Dialogue = "内部情报。不能对外说。",
    Next = 18  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#18
-- Position: { 9400, 150 }
DialogueConfig[18] = {
    Type = "Normal",
    DocTag = "2-A#18",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "总得说点什么吧。",
    Next = 19  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#19
-- Position: { 9750, 150 }
DialogueConfig[19] = {
    Type = "Normal",
    DocTag = "2-A#19",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（米粒和豆豆对视一眼）",
    Next = 20  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#20
-- Position: { 10100, 150 }
DialogueConfig[20] = {
    Type = "Normal",
    DocTag = "2-A#20",
    NpcName = "米粒",
    NpcSprite = "装酷",
    Dialogue = "……我们忙着呢。真的。",
    Next = 21  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#21
-- Position: { 10450, 150 }
DialogueConfig[21] = {
    Type = "Normal",
    DocTag = "2-A#21",
    NpcName = "豆豆",
    NpcSprite = "装酷",
    Dialogue = "对。外勤任务排满了。",
    Next = 22  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#22
-- Position: { 10800, 150 }
DialogueConfig[22] = {
    Type = "Normal",
    DocTag = "2-A#22",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（瓜子低着头，喙动了动，没出声）",
    SetVariables = {
        { VarName = "ChickStatus", VarType = "int", Value = 1 }
    },
    Next = 182  -- 下一段对话ID
}

-- 提问类型（玩家需要选择回答）  -- doc:2-hub
-- Position: { 11250, 150 }
DialogueConfig[23] = {
    Type = "Question",
    DocTag = "2-hub",
    NpcName = "阿满",
    NpcSprite = "装酷",
    Dialogue = "……还有什么事吗？",
    Options = {
        {
            Text = "你们到底在搞什么鬼？",
            Next = 24,
            DisplayConditions = {
                { VarName = "ChickTraceCount", VarType = "int", Op = ">=", Value = 2 },
                { VarName = "ChickStatus", VarType = "int", Op = "==", Value = 1 },
                { VarName = "BlackCat_CaseLineStarted", VarType = "bool", Value = false }
            },
        },
        {
            Text = "谷仓角落草窝，知道谁的吗？",
            Next = 45,
            DisplayConditions = {
                { VarName = "E07_ViewNapSpot", VarType = "bool", Value = true },
                { VarName = "Chick_NapSpotAsked", VarType = "bool", Value = false }
            },
        },
        {
            Text = "大黄宿醉那样，怎么叫醒？",
            Next = 51,
            DisplayConditions = {
                { VarName = "DogStatus", VarType = "int", Op = "==", Value = 2 },
                { VarName = "Chick_WakeDogHintShown", VarType = "bool", Value = false }
            },
        },
        {
            Text = "这玩意儿，你们怎么解释？",
            Next = 74,
            DisplayConditions = {
                { VarName = "E10_ViewWhiteStone", VarType = "bool", Value = true },
                { VarName = "ChickStatus", VarType = "int", Op = "<=", Value = 2 },
                { VarName = "BlackCat_CaseLineStarted", VarType = "bool", Value = false }
            },
        },
        {
            Text = "我准备上谷仓顶找乌鸦。",
            Next = 60,
            DisplayConditions = {
                { VarName = "DogStatus", VarType = "int", Op = ">=", Value = 2 },
                { VarName = "E10_ViewWhiteStone", VarType = "bool", Value = false },
                { VarName = "Chick_RoofBlockShown", VarType = "bool", Value = false }
            },
        },
        {
            Text = "我准备上谷仓顶找乌鸦。",
            Next = 60,
            DisplayConditions = {
                { VarName = "E06_LadderBorrowed", VarType = "bool", Value = true },
                { VarName = "E10_ViewWhiteStone", VarType = "bool", Value = false },
                { VarName = "Chick_RoofBlockShown", VarType = "bool", Value = false }
            },
        },
        {
            Text = "没事，走了。",
            Next = -1,
        }
    }
}

-- 普通对话类型  -- doc:2-B#1
-- Position: { 11700, 150 }
DialogueConfig[24] = {
    Type = "Normal",
    DocTag = "2-B#1",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "你们到底在搞什么鬼？",
    Next = 25  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-B#2
-- Position: { 12050, 150 }
DialogueConfig[25] = {
    Type = "Normal",
    DocTag = "2-B#2",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "鸡舍边上那些乱七八糟的痕迹——和你们有关吧。",
    Next = 26  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-B#3
-- Position: { 12400, 150 }
DialogueConfig[26] = {
    Type = "Normal",
    DocTag = "2-B#3",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（阿满脖子一缩）",
    Next = 28  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-B#5
-- Position: { 13100, 150 }
DialogueConfig[28] = {
    Type = "Normal",
    DocTag = "2-B#5",
    NpcName = "阿满",
    NpcSprite = "心虚",
    Dialogue = "……那是……",
    Next = 29  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-B#6
-- Position: { 13450, 150 }
DialogueConfig[29] = {
    Type = "Normal",
    DocTag = "2-B#6",
    NpcName = "米粒",
    NpcSprite = "心虚",
    Dialogue = "侦、侦探工具……",
    Next = 30  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-B#7
-- Position: { 13800, 150 }
DialogueConfig[30] = {
    Type = "Normal",
    DocTag = "2-B#7",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（四只小鸡挤得更紧）",
    Next = 31  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-B#8
-- Position: { 14150, 150 }
DialogueConfig[31] = {
    Type = "Normal",
    DocTag = "2-B#8",
    NpcName = "玩家",
    NpcSprite = "惊讶",
    Dialogue = "说！有什么事瞒着我！",
    Next = 32  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-B#9
-- Position: { 14500, 150 }
DialogueConfig[32] = {
    Type = "Normal",
    DocTag = "2-B#9",
    NpcName = "瓜子",
    NpcSprite = "心虚",
    Dialogue = "（哭腔）水怪……水怪把弟弟叼走了……",
    Next = 33  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-B#10
-- Position: { 14850, 150 }
DialogueConfig[33] = {
    Type = "Normal",
    DocTag = "2-B#10",
    NpcName = "阿满",
    NpcSprite = "心虚",
    Dialogue = "对！！就是水怪！！",
    Next = 34  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-B#11
-- Position: { 15200, 150 }
DialogueConfig[34] = {
    Type = "Normal",
    DocTag = "2-B#11",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（阿满朝池塘方向猛点头）",
    Next = 35  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-B#12
-- Position: { 15550, 150 }
DialogueConfig[35] = {
    Type = "Normal",
    DocTag = "2-B#12",
    NpcName = "阿满",
    NpcSprite = "心虚",
    Dialogue = "三个脑袋！浑身绿色！",
    Next = 36  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-B#13
-- Position: { 15900, 150 }
DialogueConfig[36] = {
    Type = "Normal",
    DocTag = "2-B#13",
    NpcName = "阿满",
    NpcSprite = "心虚",
    Dialogue = "从池塘爬上来！把蛋拖进水里了！！",
    Next = 37  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-B#14
-- Position: { 16250, 150 }
DialogueConfig[37] = {
    Type = "Normal",
    DocTag = "2-B#14",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "你亲眼看见的？",
    Next = 38  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-B#15
-- Position: { 16600, 150 }
DialogueConfig[38] = {
    Type = "Normal",
    DocTag = "2-B#15",
    NpcName = "阿满",
    NpcSprite = "心虚",
    Dialogue = "没、没看见……但肯定是！！",
    Next = 39  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-B#16
-- Position: { 16950, 150 }
DialogueConfig[39] = {
    Type = "Normal",
    DocTag = "2-B#16",
    NpcName = "阿满",
    NpcSprite = "心虚",
    Dialogue = "昨晚外面那声音……青蛙也说过……",
    Next = 40  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-B#17
-- Position: { 17300, 150 }
DialogueConfig[40] = {
    Type = "Normal",
    DocTag = "2-B#17",
    NpcName = "阿满",
    NpcSprite = "心虚",
    Dialogue = "（发颤）不然弟弟怎么会不见……",
    Next = 41  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-B#18
-- Position: { 17650, 150 }
DialogueConfig[41] = {
    Type = "Normal",
    DocTag = "2-B#18",
    NpcName = "豆豆",
    NpcSprite = "心虚",
    Dialogue = "池塘那只青蛙肯定见过！！",
    Next = 42  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-B#19
-- Position: { 18000, 150 }
DialogueConfig[42] = {
    Type = "Normal",
    DocTag = "2-B#19",
    NpcName = "米粒",
    NpcSprite = "心虚",
    Dialogue = "快去问他！！求你快去！！",
    Next = 43  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-B#20
-- Position: { 18350, 150 }
DialogueConfig[43] = {
    Type = "Normal",
    DocTag = "2-B#20",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（阿满墨镜歪了，顾不上扶）",
    Next = 44  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-B#21
-- Position: { 18700, 150 }
DialogueConfig[44] = {
    Type = "Normal",
    DocTag = "2-B#21",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（……）",
    SetVariables = {
        { VarName = "ChickStatus", VarType = "int", Value = 2 },
        { VarName = "Chick_HubFromSubItem", VarType = "bool", Value = true },
    },
    Next = 182  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-C#1
-- Position: { 3450, 700 }
DialogueConfig[45] = {
    Type = "Normal",
    DocTag = "2-C#1",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "谷仓角落有个草窝，你们知道是谁的吗？",
    Next = 46  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-C#2
-- Position: { 3800, 700 }
DialogueConfig[46] = {
    Type = "Normal",
    DocTag = "2-C#2",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（阿满皱眉）",
    Next = 47  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-C#3
-- Position: { 4150, 700 }
DialogueConfig[47] = {
    Type = "Normal",
    DocTag = "2-C#3",
    NpcName = "阿满",
    NpcSprite = "装酷",
    Dialogue = "谷仓角落？不在我们巡逻范围。",
    Next = 48  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-C#4
-- Position: { 4500, 700 }
DialogueConfig[48] = {
    Type = "Normal",
    DocTag = "2-C#4",
    NpcName = "米粒",
    NpcSprite = "装酷",
    Dialogue = "（小声）我……我没注意那边。",
    Next = 49  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-C#5
-- Position: { 4850, 700 }
DialogueConfig[49] = {
    Type = "Normal",
    DocTag = "2-C#5",
    NpcName = "豆豆",
    NpcSprite = "装酷",
    Dialogue = "问错地方了！我们只守鸡舍这边！",
    Next = 50  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-C#6
-- Position: { 5200, 700 }
DialogueConfig[50] = {
    Type = "Normal",
    DocTag = "2-C#6",
    NpcName = "阿满",
    NpcSprite = "装酷",
    Dialogue = "……没什么好说的。",
    SetVariables = {
        { VarName = "Chick_NapSpotAsked", VarType = "bool", Value = true },
        { VarName = "Chick_HubFromSubItem", VarType = "bool", Value = true },
    },
    Next = 182  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-D#1
-- Position: { 18700, 700 }
DialogueConfig[51] = {
    Type = "Normal",
    DocTag = "2-D#1",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "大黄宿醉成那样，有什么法子叫醒他吗？",
    Next = 52  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-D#2
-- Position: { 19050, 700 }
DialogueConfig[52] = {
    Type = "Normal",
    DocTag = "2-D#2",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（豆豆蹦了一下，墨镜歪了）",
    Next = 53  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-D#3
-- Position: { 19400, 700 }
DialogueConfig[53] = {
    Type = "Normal",
    DocTag = "2-D#3",
    NpcName = "豆豆",
    NpcSprite = "装酷",
    Dialogue = "大黄叔叔？他还在那儿躺着？！",
    Next = 54  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-D#4
-- Position: { 19750, 700 }
DialogueConfig[54] = {
    Type = "Normal",
    DocTag = "2-D#4",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（阿满按住豆豆）",
    Next = 55  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-D#5
-- Position: { 20100, 700 }
DialogueConfig[55] = {
    Type = "Normal",
    DocTag = "2-D#5",
    NpcName = "阿满",
    NpcSprite = "装酷",
    Dialogue = "……嗯。",
    Next = 56  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-D#6
-- Position: { 20450, 700 }
DialogueConfig[56] = {
    Type = "Normal",
    DocTag = "2-D#6",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "有办法吗？",
    Next = 57  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-D#7
-- Position: { 20800, 700 }
DialogueConfig[57] = {
    Type = "Normal",
    DocTag = "2-D#7",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（阿满压低声音，翅膀尖抖了一下）",
    Next = 58  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-D#8
-- Position: { 21150, 700 }
DialogueConfig[58] = {
    Type = "Normal",
    DocTag = "2-D#8",
    NpcName = "阿满",
    NpcSprite = "装酷",
    Dialogue = "鸡舍水槽边，有老谷物泡的水。他爱喝。灌下去就醒。……拿去，算侦探团对前辈的关照。",
    Next = 59  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-D#9
-- Position: { 21500, 700 }
DialogueConfig[59] = {
    Type = "Normal",
    DocTag = "2-D#9",
    NpcName = "瓜子",
    NpcSprite = "装酷",
    Dialogue = "（小声）……这次能帮上忙吗？",
    SetVariables = {
        { VarName = "Chick_WakeDogHintShown", VarType = "bool", Value = true },
        { VarName = "Chick_HubFromSubItem", VarType = "bool", Value = true },
    },
    Next = 182  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-F#1
-- Position: { 3450, 1250 }
DialogueConfig[60] = {
    Type = "Normal",
    DocTag = "2-F#1",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "我准备上谷仓顶找乌鸦。",
    Next = 61  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-F#2
-- Position: { 3800, 1250 }
DialogueConfig[61] = {
    Type = "Normal",
    DocTag = "2-F#2",
    NpcName = "豆豆",
    NpcSprite = "心虚",
    Dialogue = "啊？谷仓顶上有什么？",
    Next = 62  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-F#3
-- Position: { 4150, 1250 }
DialogueConfig[62] = {
    Type = "Normal",
    DocTag = "2-F#3",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "大黄说——乌鸦把蛋叼上屋顶了。",
    Next = 220
}

DialogueConfig[220] = {
    Type = "Normal",
    DocTag = "2-F#3b",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（四只小鸡僵住）",
    Next = 63
}

-- 普通对话类型  -- doc:2-F#4
-- Position: { 4500, 1250 }
DialogueConfig[63] = {
    Type = "Normal",
    DocTag = "2-F#4",
    NpcName = "阿满",
    NpcSprite = "心虚",
    Dialogue = "……屋顶？",
    Next = 64  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-F#5
-- Position: { 4850, 1250 }
DialogueConfig[64] = {
    Type = "Normal",
    DocTag = "2-F#5",
    NpcName = "米粒",
    NpcSprite = "心虚",
    Dialogue = "（小声）蛋……？",
    Next = 65  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-F#6
-- Position: { 5200, 1250 }
DialogueConfig[65] = {
    Type = "Normal",
    DocTag = "2-F#6",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "乌鸦还守在上面。我得上去看看。",
    Next = 66  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-F#7
-- Position: { 5550, 1250 }
DialogueConfig[66] = {
    Type = "Normal",
    DocTag = "2-F#7",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（阿满跟另外三只对视一眼；豆豆嘴张了张，没出声）",
    Next = 67  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-F#8
-- Position: { 5900, 1250 }
DialogueConfig[67] = {
    Type = "Normal",
    DocTag = "2-F#8",
    NpcName = "瓜子",
    NpcSprite = "心虚",
    Dialogue = "（极小声）会不会是……",
    Next = 68  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-F#9
-- Position: { 6250, 1250 }
DialogueConfig[68] = {
    Type = "Normal",
    DocTag = "2-F#9",
    NpcName = "阿满",
    NpcSprite = "心虚",
    Dialogue = "（急）瓜子！",
    Next = 69  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-F#10
-- Position: { 6600, 1250 }
DialogueConfig[69] = {
    Type = "Normal",
    DocTag = "2-F#10",
    NpcName = "玩家",
    NpcSprite = "惊讶",
    Dialogue = "什么？",
    Next = 70  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-F#11
-- Position: { 6950, 1250 }
DialogueConfig[70] = {
    Type = "Normal",
    DocTag = "2-F#11",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（风从鸡舍边吹过）",
    Next = 71  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-F#12
-- Position: { 7300, 1250 }
DialogueConfig[71] = {
    Type = "Normal",
    DocTag = "2-F#12",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（四只小鸡谁也不看谁）",
    Next = 72  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-F#13
-- Position: { 7650, 1250 }
DialogueConfig[72] = {
    Type = "Normal",
    DocTag = "2-F#13",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（阿满想扶墨镜，又僵住）",
    Next = 73  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-F#14
-- Position: { 8000, 1250 }
DialogueConfig[73] = {
    Type = "Normal",
    DocTag = "2-F#14",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（四只小鸡一起闭嘴了）",
    SetVariables = {
        { VarName = "Chick_RoofBlockShown", VarType = "bool", Value = true },
        { VarName = "Chick_HubFromSubItem", VarType = "bool", Value = true },
    },
    Next = 182  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#1
-- Position: { 5650, 700 }
DialogueConfig[74] = {
    Type = "Normal",
    DocTag = "2-E#1",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "你们猜，我千辛万苦爬上去，在乌鸦那儿找到什么了？",
    Next = 75  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#2
-- Position: { 6000, 700 }
DialogueConfig[75] = {
    Type = "Normal",
    DocTag = "2-E#2",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（四只小鸡对视，谁也不说话）",
    Next = 76  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#3
-- Position: { 6350, 700 }
DialogueConfig[76] = {
    Type = "Normal",
    DocTag = "2-E#3",
    NpcName = "米粒",
    NpcSprite = "愧疚",
    Dialogue = "……蛋？",
    Next = 77  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#4
-- Position: { 6700, 700 }
DialogueConfig[77] = {
    Type = "Normal",
    DocTag = "2-E#4",
    NpcName = "玩家",
    NpcSprite = "惊讶",
    Dialogue = "说！这是什么！怎么回事！",
    Next = 78  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#5
-- Position: { 7050, 700 }
DialogueConfig[78] = {
    Type = "Normal",
    DocTag = "2-E#5",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（四只小鸡凑过来，又猛地僵住）",
    Next = 79  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#6
-- Position: { 7400, 700 }
DialogueConfig[79] = {
    Type = "Normal",
    DocTag = "2-E#6",
    NpcName = "瓜子",
    NpcSprite = "愧疚",
    Dialogue = "……是我们画的。",
    Next = 80  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#7
-- Position: { 7750, 700 }
DialogueConfig[80] = {
    Type = "Normal",
    DocTag = "2-E#7",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（墨镜啪嗒落地）",
    Next = 81  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#8
-- Position: { 8100, 700 }
DialogueConfig[81] = {
    Type = "Normal",
    DocTag = "2-E#8",
    NpcName = "阿满",
    NpcSprite = "愧疚",
    Dialogue = "那不是老妈的蛋……乌鸦叼走的是假的……",
    Next = 82  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#9
-- Position: { 8450, 700 }
DialogueConfig[82] = {
    Type = "Normal",
    DocTag = "2-E#9",
    NpcName = "阿满",
    NpcSprite = "愧疚",
    Dialogue = "（哭）那弟弟呢——弟弟到底在哪——",
    Next = 83  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#10
-- Position: { 8800, 700 }
DialogueConfig[83] = {
    Type = "Normal",
    DocTag = "2-E#10",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（阿满翅膀捂住脸）",
    Next = 84  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#11
-- Position: { 9150, 700 }
DialogueConfig[84] = {
    Type = "Normal",
    DocTag = "2-E#11",
    NpcName = "阿满",
    NpcSprite = "愧疚",
    Dialogue = "呜呜呜——我招了！！",
    Next = 85  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#12
-- Position: { 9500, 700 }
DialogueConfig[85] = {
    Type = "Normal",
    DocTag = "2-E#12",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "从头说。",
    Next = 86  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#13
-- Position: { 9850, 700 }
DialogueConfig[86] = {
    Type = "Normal",
    DocTag = "2-E#13",
    NpcName = "阿满",
    NpcSprite = "愧疚",
    Dialogue = "大前天下午，我们捡了块白石头，画成蛋的样子，放进窝里假装是蛋，",
    Next = 87  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#14
-- Position: { 10200, 700 }
DialogueConfig[87] = {
    Type = "Normal",
    DocTag = "2-E#14",
    NpcName = "阿满",
    NpcSprite = "愧疚",
    Dialogue = "然后把真的弟弟偷出来——",
    Next = 88  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#15
-- Position: { 10550, 700 }
DialogueConfig[88] = {
    Type = "Normal",
    DocTag = "2-E#15",
    NpcName = "米粒",
    NpcSprite = "心虚",
    Dialogue = "（小声）踢球。",
    Next = 89  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#16
-- Position: { 10900, 700 }
DialogueConfig[89] = {
    Type = "Normal",
    DocTag = "2-E#16",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "踢……球？你们拿弟弟当球踢？",
    Next = 90  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#17
-- Position: { 11250, 700 }
DialogueConfig[90] = {
    Type = "Normal",
    DocTag = "2-E#17",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（几只小鸡低头不语）",
    Next = 91  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#18
-- Position: { 11600, 700 }
DialogueConfig[91] = {
    Type = "Normal",
    DocTag = "2-E#18",
    NpcName = "玩家",
    NpcSprite = "惊讶",
    Dialogue = "然后呢？",
    Next = 221
}

DialogueConfig[221] = {
    Type = "Normal",
    DocTag = "2-E#18b",
    NpcName = "阿满",
    NpcSprite = "愧疚",
    Dialogue = "推着弟弟路过谷仓时，老鼠叔叔蹿出来说——",
    Next = 92
}

-- 普通对话类型  -- doc:2-E#19
-- Position: { 11950, 700 }
DialogueConfig[92] = {
    Type = "Normal",
    DocTag = "2-E#19",
    NpcName = "阿满",
    NpcSprite = "愧疚",
    Dialogue = "有沼泽水怪，晚上爬出来，专门吃沾了泥土的蛋！",
    Next = 93  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#20
-- Position: { 12300, 700 }
DialogueConfig[93] = {
    Type = "Normal",
    DocTag = "2-E#20",
    NpcName = "豆豆",
    NpcSprite = "心虚",
    Dialogue = "（气鼓鼓）现在想起来他们全程在憋笑！！",
    Next = 222
}

DialogueConfig[222] = {
    Type = "Normal",
    DocTag = "2-E#20b",
    NpcName = "阿满",
    NpcSprite = "愧疚",
    Dialogue = "我们吓得跑去池塘洗蛋，又被青蛙的话吓着了——",
    Next = 94
}

-- 普通对话类型  -- doc:2-E#21
-- Position: { 12650, 700 }
DialogueConfig[94] = {
    Type = "Normal",
    DocTag = "2-E#21",
    NpcName = "阿满",
    NpcSprite = "愧疚",
    Dialogue = "赶紧把真蛋推回窝里！",
    Next = 95  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#22
-- Position: { 13000, 700 }
DialogueConfig[95] = {
    Type = "Normal",
    DocTag = "2-E#22",
    NpcName = "玩家",
    NpcSprite = "惊讶",
    Dialogue = "假石头呢？",
    Next = 96  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#23
-- Position: { 13350, 700 }
DialogueConfig[96] = {
    Type = "Normal",
    DocTag = "2-E#23",
    NpcName = "米粒",
    NpcSprite = "愧疚",
    Dialogue = "假石头嘛……大前天随手扔进草丛了……",
    Next = 97  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#24
-- Position: { 13700, 700 }
DialogueConfig[97] = {
    Type = "Normal",
    DocTag = "2-E#24",
    NpcName = "瓜子",
    NpcSprite = "心虚",
    Dialogue = "（小声）后来……被乌鸦叼走了。",
    Next = 98  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#25
-- Position: { 14050, 700 }
DialogueConfig[98] = {
    Type = "Normal",
    DocTag = "2-E#25",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "那大黄说乌鸦叼蛋上屋顶——？",
    Next = 99  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#26
-- Position: { 14400, 700 }
DialogueConfig[99] = {
    Type = "Normal",
    DocTag = "2-E#26",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（四只小鸡对视）",
    Next = 100  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#27
-- Position: { 14750, 700 }
DialogueConfig[100] = {
    Type = "Normal",
    DocTag = "2-E#27",
    NpcName = "米粒",
    NpcSprite = "心虚",
    Dialogue = "大黄叔叔喝了两天酒，日子都搅糊涂了……",
    Next = 101  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#28
-- Position: { 15100, 700 }
DialogueConfig[101] = {
    Type = "Normal",
    DocTag = "2-E#28",
    NpcName = "阿满",
    NpcSprite = "愧疚",
    Dialogue = "（哭）乌鸦叼走的是我们画的假石头——大前天的事！",
    Next = 223
}

DialogueConfig[223] = {
    Type = "Normal",
    DocTag = "2-E#28b",
    NpcName = "阿满",
    NpcSprite = "心虚",
    Dialogue = "弟弟是昨晚才不见的！跟那一趟不是一回事！",
    Next = 102
}

-- 普通对话类型  -- doc:2-E#29
-- Position: { 15450, 700 }
DialogueConfig[102] = {
    Type = "Normal",
    DocTag = "2-E#29",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "昨晚有动静吗？",
    Next = 103  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#30
-- Position: { 15800, 700 }
DialogueConfig[103] = {
    Type = "Normal",
    DocTag = "2-E#30",
    NpcName = "豆豆",
    NpcSprite = "愧疚",
    Dialogue = "睡前弟弟还在……半夜一看，窝空了……",
    Next = 104  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#31
-- Position: { 16150, 700 }
DialogueConfig[104] = {
    Type = "Normal",
    DocTag = "2-E#31",
    NpcName = "米粒",
    NpcSprite = "心虚",
    Dialogue = "外面有好响的声音……我们以为是水怪……",
    Next = 105  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#32
-- Position: { 16500, 700 }
DialogueConfig[105] = {
    Type = "Normal",
    DocTag = "2-E#32",
    NpcName = "阿满",
    NpcSprite = "愧疚",
    Dialogue = "（哭）如果没有水怪……到底是谁带走了弟弟？",
    Next = 106  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#33
-- Position: { 16850, 700 }
DialogueConfig[106] = {
    Type = "Normal",
    DocTag = "2-E#33",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（阿满瘫坐）",
    Next = 107  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#34
-- Position: { 17200, 700 }
DialogueConfig[107] = {
    Type = "Normal",
    DocTag = "2-E#34",
    NpcName = "瓜子",
    NpcSprite = "愧疚",
    Dialogue = "……以后再也不偷弟弟出去踢球了。",
    Next = 108  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#35
-- Position: { 17550, 700 }
DialogueConfig[108] = {
    Type = "Normal",
    DocTag = "2-E#35",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（鸡舍里很安静）",
    Next = 109  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#36
-- Position: { 17900, 700 }
DialogueConfig[109] = {
    Type = "Normal",
    DocTag = "2-E#36",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（……）",
    Next = 110  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#37
-- Position: { 18250, 700 }
DialogueConfig[110] = {
    Type = "Normal",
    DocTag = "2-E#37",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（鸡舍里很安静）",
    SetVariables = {
        { VarName = "ChickStatus", VarType = "int", Value = 3 },
        { VarName = "Chick_HubFromSubItem", VarType = "bool", Value = true },
    },
    Next = 182  -- 下一段对话ID
}

-- 普通对话类型  -- doc:3-A@v1#1
-- Position: { 50, 50 }
DialogueConfig[111] = {
    Type = "Normal",
    DocTag = "3-A@v1#1",
    NpcName = "豆豆",
    NpcSprite = "心虚",
    Dialogue = "（极小声）大侦探……",
    Next = 112  -- 下一段对话ID
}

-- 普通对话类型  -- doc:3-A@v1#2
-- Position: { 400, 50 }
DialogueConfig[112] = {
    Type = "Normal",
    DocTag = "3-A@v1#2",
    NpcName = "瓜子",
    NpcSprite = "心虚",
    Dialogue = "（更小声）别看我……",
    Next = 113  -- 下一段对话ID
}

-- 普通对话类型  -- doc:3-A@v1#3
-- Position: { 750, 50 }
DialogueConfig[113] = {
    Type = "Normal",
    DocTag = "3-A@v1#3",
    NpcName = "阿满",
    NpcSprite = "愧疚",
    Dialogue = "（压声）站好。",
    Next = 114  -- 下一段对话ID
}

-- 普通对话类型  -- doc:3-A@v1#4
-- Position: { 1100, 50 }
DialogueConfig[114] = {
    Type = "Normal",
    DocTag = "3-A@v1#4",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "淑芬还在哭。",
    Next = 115  -- 下一段对话ID
}

-- 普通对话类型  -- doc:3-A@v1#5
-- Position: { 1450, 50 }
DialogueConfig[115] = {
    Type = "Normal",
    DocTag = "3-A@v1#5",
    NpcName = "阿满",
    NpcSprite = "愧疚",
    Dialogue = "……我们知道。",
    Next = 116  -- 下一段对话ID
}

-- 普通对话类型  -- doc:3-A@v1#6
-- Position: { 1800, 50 }
DialogueConfig[116] = {
    Type = "Normal",
    DocTag = "3-A@v1#6",
    NpcName = "瓜子",
    NpcSprite = "愧疚",
    Dialogue = "（哭腔）是我们害的……",
    SetVariables = {
        { VarName = "Chick_Chapter2GuiltShown", VarType = "bool", Value = true }
    },
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:3-A@v2#1
-- Position: { 50, 330 }
DialogueConfig[117] = {
    Type = "Normal",
    DocTag = "3-A@v2#1",
    NpcName = "米粒",
    NpcSprite = "愧疚",
    Dialogue = "大侦探。",
    Next = 118  -- 下一段对话ID
}

-- 普通对话类型  -- doc:3-A@v2#2
-- Position: { 400, 330 }
DialogueConfig[118] = {
    Type = "Normal",
    DocTag = "3-A@v2#2",
    NpcName = "玩家",
    NpcSprite = "惊讶",
    Dialogue = "嗯？",
    Next = 119  -- 下一段对话ID
}

-- 普通对话类型  -- doc:3-A@v2#3
-- Position: { 750, 330 }
DialogueConfig[119] = {
    Type = "Normal",
    DocTag = "3-A@v2#3",
    NpcName = "米粒",
    NpcSprite = "心虚",
    Dialogue = "要是……要是弟弟真在红顶屋……",
    Next = 120  -- 下一段对话ID
}

-- 普通对话类型  -- doc:3-A@v2#4
-- Position: { 1100, 330 }
DialogueConfig[120] = {
    Type = "Normal",
    DocTag = "3-A@v2#4",
    NpcName = "米粒",
    NpcSprite = "愧疚",
    Dialogue = "我们就去认错。",
    Next = 121  -- 下一段对话ID
}

-- 普通对话类型  -- doc:3-A@v2#5
-- Position: { 1450, 330 }
DialogueConfig[121] = {
    Type = "Normal",
    DocTag = "3-A@v2#5",
    NpcName = "阿满",
    NpcSprite = "心虚",
    Dialogue = "（小声）……嗯。",
    Next = 122  -- 下一段对话ID
}

-- 普通对话类型  -- doc:3-A@v2#6
-- Position: { 1800, 330 }
DialogueConfig[122] = {
    Type = "Normal",
    DocTag = "3-A@v2#6",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "还不确定。",
    Next = 123  -- 下一段对话ID
}

-- 普通对话类型  -- doc:3-A@v2#7
-- Position: { 2150, 150 }
DialogueConfig[123] = {
    Type = "Normal",
    DocTag = "3-A@v2#7",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（阿满点了一下头）",
    SetVariables = {
        { VarName = "Chick_Chapter2GuiltShown", VarType = "bool", Value = true }
    },
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:3-A@v3#1
-- Position: { 50, 610 }
DialogueConfig[124] = {
    Type = "Normal",
    DocTag = "3-A@v3#1",
    NpcName = "玩家",
    NpcSprite = "惊讶",
    Dialogue = "后悔吗？",
    Next = 125  -- 下一段对话ID
}

-- 普通对话类型  -- doc:3-A@v3#2
-- Position: { 400, 610 }
DialogueConfig[125] = {
    Type = "Normal",
    DocTag = "3-A@v3#2",
    NpcName = "小鸡们",
    NpcSprite = "愧疚",
    Dialogue = "（四只小鸡都不吭声）",
    Next = 126  -- 下一段对话ID
}

-- 普通对话类型  -- doc:3-A@v3#3
-- Position: { 750, 610 }
DialogueConfig[126] = {
    Type = "Normal",
    DocTag = "3-A@v3#3",
    NpcName = "瓜子",
    NpcSprite = "愧疚",
    Dialogue = "……后悔。",
    Next = 127  -- 下一段对话ID
}

-- 普通对话类型  -- doc:3-A@v3#4
-- Position: { 1100, 610 }
DialogueConfig[127] = {
    Type = "Normal",
    DocTag = "3-A@v3#4",
    NpcName = "阿满",
    NpcSprite = "愧疚",
    Dialogue = "（哑）暗影侦探团……搞砸了。",
    Next = 128  -- 下一段对话ID
}

-- 普通对话类型  -- doc:3-A@v3#5
-- Position: { 1450, 610 }
DialogueConfig[128] = {
    Type = "Normal",
    DocTag = "3-A@v3#5",
    NpcName = "豆豆",
    NpcSprite = "心虚",
    Dialogue = "我……再也不乱喊水怪了。",
    Next = 129  -- 下一段对话ID
}

-- 普通对话类型  -- doc:3-A@v3#6
-- Position: { 1800, 610 }
DialogueConfig[129] = {
    Type = "Normal",
    DocTag = "3-A@v3#6",
    NpcName = "阿满",
    NpcSprite = "装酷",
    Dialogue = "别再提了。",
    SetVariables = {
        { VarName = "Chick_Chapter2GuiltShown", VarType = "bool", Value = true }
    },
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:3-A
-- Position: { 50, 890 }
DialogueConfig[130] = {
    Type = "Normal",
    DocTag = "3-A",
    NpcName = "小鸡们",
    NpcSprite = "装酷",
    Dialogue = "",
    RotatePool = { 111, 117, 124 },
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus#2
-- Position: { 3450, 2550 }
DialogueConfig[131] = {
    Type = "Normal",
    DocTag = "NGPlus#2",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（四只小鸡坐在鸡舍门口；阿满墨镜搁在脚边）",
    Next = 132  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus#3
-- Position: { 3800, 2550 }
DialogueConfig[132] = {
    Type = "Normal",
    DocTag = "NGPlus#3",
    NpcName = "阿满",
    NpcSprite = "愧疚",
    Dialogue = "……你来了。",
    Next = 133  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus#4
-- Position: { 4150, 2550 }
DialogueConfig[133] = {
    Type = "Normal",
    DocTag = "NGPlus#4",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "告诉你们一个好消息——弟弟出壳了。",
    Next = 134  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus#5
-- Position: { 4500, 2550 }
DialogueConfig[134] = {
    Type = "Normal",
    DocTag = "NGPlus#5",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（四只小鸡抬起头）",
    Next = 135  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus#6
-- Position: { 4850, 2550 }
DialogueConfig[135] = {
    Type = "Normal",
    DocTag = "NGPlus#6",
    NpcName = "瓜子",
    NpcSprite = "愧疚",
    Dialogue = "……真的出来了？",
    Next = 136  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus#7
-- Position: { 5200, 2550 }
DialogueConfig[136] = {
    Type = "Normal",
    DocTag = "NGPlus#7",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "出来了。自己在窝里叫呢。",
    Next = 137  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus#8
-- Position: { 5550, 2650 }
DialogueConfig[137] = {
    Type = "Normal",
    DocTag = "NGPlus#8",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（豆豆扭头，翅膀蹭眼睛）",
    Next = 138  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus#9
-- Position: { 5900, 2650 }
DialogueConfig[138] = {
    Type = "Normal",
    DocTag = "NGPlus#9",
    NpcName = "豆豆",
    NpcSprite = "愧疚",
    Dialogue = "我没哭。",
    Next = 139  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus#10
-- Position: { 6250, 2650 }
DialogueConfig[139] = {
    Type = "Normal",
    DocTag = "NGPlus#10",
    NpcName = "阿满",
    NpcSprite = "愧疚",
    Dialogue = "……那段日子，我们天天盼他没事。",
    Next = 140  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus#11
-- Position: { 6600, 2650 }
DialogueConfig[140] = {
    Type = "Normal",
    DocTag = "NGPlus#11",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "现在好了。",
    Next = 141  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus#12
-- Position: { 6950, 2650 }
DialogueConfig[141] = {
    Type = "Normal",
    DocTag = "NGPlus#12",
    NpcName = "阿满",
    NpcSprite = "愧疚",
    Dialogue = "（低声）嗯……其实当时，怕得很。",
    Next = 142  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus#13
-- Position: { 7300, 2650 }
DialogueConfig[142] = {
    Type = "Normal",
    DocTag = "NGPlus#13",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "那老鼠骗你们编水怪的事——还打算算账吗？",
    Next = 143  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus#14
-- Position: { 7650, 2650 }
DialogueConfig[143] = {
    Type = "Normal",
    DocTag = "NGPlus#14",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（豆豆翅膀一举）",
    Next = 144  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus#15
-- Position: { 8000, 2650 }
DialogueConfig[144] = {
    Type = "Normal",
    DocTag = "NGPlus#15",
    NpcName = "豆豆",
    NpcSprite = "愧疚",
    Dialogue = "要算！！非得找他们算！！",
    Next = 145  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus#16
-- Position: { 8350, 2650 }
DialogueConfig[145] = {
    Type = "Normal",
    DocTag = "NGPlus#16",
    NpcName = "阿满",
    NpcSprite = "装酷",
    Dialogue = "（打断）……",
    Next = 146  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus#17
-- Position: { 8700, 2650 }
DialogueConfig[146] = {
    Type = "Normal",
    DocTag = "NGPlus#17",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（阿满重新戴上墨镜）",
    Next = 147  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus#18
-- Position: { 9050, 2650 }
DialogueConfig[147] = {
    Type = "Normal",
    DocTag = "NGPlus#18",
    NpcName = "阿满",
    NpcSprite = "装酷",
    Dialogue = "暗影侦探团自有安排。",
    Next = 148  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus#19
-- Position: { 9400, 2650 }
DialogueConfig[148] = {
    Type = "Normal",
    DocTag = "NGPlus#19",
    NpcName = "豆豆",
    NpcSprite = "愧疚",
    Dialogue = "（小声）他们编得也太过分了……",
    Next = 149  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus#20
-- Position: { 9750, 2650 }
DialogueConfig[149] = {
    Type = "Normal",
    DocTag = "NGPlus#20",
    NpcName = "阿满",
    NpcSprite = "愧疚",
    Dialogue = "（压声）豆豆，听见了。",
    Next = 150  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus#21
-- Position: { 10100, 2650 }
DialogueConfig[150] = {
    Type = "Normal",
    DocTag = "NGPlus#21",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（豆豆用力点头；米粒、瓜子也跟着点）",
    SetVariables = {
        { VarName = "Chick_NGPlusShown", VarType = "bool", Value = true }
    },
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus-revisit@v1#1
-- Position: { 3450, 2830 }
DialogueConfig[156] = {
    Type = "Normal",
    DocTag = "NGPlus-revisit@v1#1",
    NpcName = "小鸡们",
    NpcSprite = "愧疚",
    Dialogue = "（四只小鸡排成一列，墨镜戴正了）",
    Next = 157  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus-revisit@v1#2
-- Position: { 3800, 2830 }
DialogueConfig[157] = {
    Type = "Normal",
    DocTag = "NGPlus-revisit@v1#2",
    NpcName = "阿满",
    NpcSprite = "愧疚",
    Dialogue = "同行。",
    Next = 158  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus-revisit@v1#3
-- Position: { 4150, 2830 }
DialogueConfig[158] = {
    Type = "Normal",
    DocTag = "NGPlus-revisit@v1#3",
    NpcName = "玩家",
    NpcSprite = "惊讶",
    Dialogue = "还有任务？",
    Next = 159  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus-revisit@v1#4
-- Position: { 4500, 2830 }
DialogueConfig[159] = {
    Type = "Normal",
    DocTag = "NGPlus-revisit@v1#4",
    NpcName = "阿满",
    NpcSprite = "愧疚",
    Dialogue = "散步。",
    Next = 160  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus-revisit@v1#5
-- Position: { 4850, 2830 }
DialogueConfig[160] = {
    Type = "Normal",
    DocTag = "NGPlus-revisit@v1#5",
    NpcName = "豆豆",
    NpcSprite = "愧疚",
    Dialogue = "（压声）顺便看老鼠在不在。",
    Next = 161  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus-revisit@v1#6
-- Position: { 5200, 2830 }
DialogueConfig[161] = {
    Type = "Normal",
    DocTag = "NGPlus-revisit@v1#6",
    NpcName = "阿满",
    NpcSprite = "愧疚",
    Dialogue = "（压声）豆豆！！",
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus-revisit@v2#1
-- Position: { 3450, 3110 }
DialogueConfig[162] = {
    Type = "Normal",
    DocTag = "NGPlus-revisit@v2#1",
    NpcName = "玩家",
    NpcSprite = "惊讶",
    Dialogue = "新案子？",
    Next = 163  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus-revisit@v2#2
-- Position: { 3800, 3110 }
DialogueConfig[163] = {
    Type = "Normal",
    DocTag = "NGPlus-revisit@v2#2",
    NpcName = "阿满",
    NpcSprite = "愧疚",
    Dialogue = "没有。弟弟刚出壳，别出去疯。",
    Next = 164  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus-revisit@v2#3
-- Position: { 4150, 3110 }
DialogueConfig[164] = {
    Type = "Normal",
    DocTag = "NGPlus-revisit@v2#3",
    NpcName = "瓜子",
    NpcSprite = "愧疚",
    Dialogue = "嗯。",
    Next = 165  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus-revisit@v2#4
-- Position: { 4500, 3110 }
DialogueConfig[165] = {
    Type = "Normal",
    DocTag = "NGPlus-revisit@v2#4",
    NpcName = "瓜子",
    NpcSprite = "愧疚",
    Dialogue = "嗯。",
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus-revisit@v3#1
-- Position: { 3450, 3390 }
DialogueConfig[166] = {
    Type = "Normal",
    DocTag = "NGPlus-revisit@v3#1",
    NpcName = "小鸡们",
    NpcSprite = "愧疚",
    Dialogue = "（瓜子盯着鸡舍里）",
    Next = 167  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus-revisit@v3#2
-- Position: { 3800, 3390 }
DialogueConfig[167] = {
    Type = "Normal",
    DocTag = "NGPlus-revisit@v3#2",
    NpcName = "玩家",
    NpcSprite = "惊讶",
    Dialogue = "看什么？",
    Next = 168  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus-revisit@v3#3
-- Position: { 4150, 3390 }
DialogueConfig[168] = {
    Type = "Normal",
    DocTag = "NGPlus-revisit@v3#3",
    NpcName = "瓜子",
    NpcSprite = "愧疚",
    Dialogue = "看弟弟。",
    Next = 169  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus-revisit@v3#4
-- Position: { 4500, 3390 }
DialogueConfig[169] = {
    Type = "Normal",
    DocTag = "NGPlus-revisit@v3#4",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（窝里传来细弱的叫声）",
    Next = 170  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus-revisit@v3#5
-- Position: { 4850, 3110 }
DialogueConfig[170] = {
    Type = "Normal",
    DocTag = "NGPlus-revisit@v3#5",
    NpcName = "瓜子",
    NpcSprite = "愧疚",
    Dialogue = "（小声）他刚才往这边看了。",
    Next = 171  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus-revisit@v3#6
-- Position: { 5200, 3110 }
DialogueConfig[171] = {
    Type = "Normal",
    DocTag = "NGPlus-revisit@v3#6",
    NpcName = "瓜子",
    NpcSprite = "愧疚",
    Dialogue = "（小声）他刚才往这边看了。",
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus-revisit
-- Position: { 3450, 3670 }
DialogueConfig[172] = {
    Type = "Normal",
    DocTag = "NGPlus-revisit",
    NpcName = "小鸡们",
    NpcSprite = "装酷",
    Dialogue = "",
    RotatePool = { 156, 162, 166 },
    Next = -1  -- 下一段对话ID
}

-- 提问类型（玩家需要选择回答）  -- doc:2-hub#s1#menu
-- Position: { 12300, 50 }
DialogueConfig[173] = {
    Type = "Question",
    DocTag = "2-hub#s1#menu",
    NpcName = "阿满",
    NpcSprite = "装酷",
    Dialogue = "……还在查。别碰我们的现场。",
    Options = {
        {
            Text = "你们到底在搞什么鬼？",
            Next = 24,
            DisplayConditions = {
                { VarName = "ChickTraceCount", VarType = "int", Op = ">=", Value = 2 },
                { VarName = "ChickStatus", VarType = "int", Op = "==", Value = 1 },
                { VarName = "BlackCat_CaseLineStarted", VarType = "bool", Value = false }
            },
        },
        {
            Text = "谷仓角落草窝，知道谁的吗？",
            Next = 45,
            DisplayConditions = {
                { VarName = "E07_ViewNapSpot", VarType = "bool", Value = true },
                { VarName = "Chick_NapSpotAsked", VarType = "bool", Value = false }
            },
        },
        {
            Text = "大黄宿醉那样，怎么叫醒？",
            Next = 51,
            DisplayConditions = {
                { VarName = "DogStatus", VarType = "int", Op = "==", Value = 2 },
                { VarName = "Chick_WakeDogHintShown", VarType = "bool", Value = false }
            },
        },
        {
            Text = "这玩意儿，你们怎么解释？",
            Next = 74,
            DisplayConditions = {
                { VarName = "E10_ViewWhiteStone", VarType = "bool", Value = true },
                { VarName = "ChickStatus", VarType = "int", Op = "<=", Value = 2 },
                { VarName = "BlackCat_CaseLineStarted", VarType = "bool", Value = false }
            },
        },
        {
            Text = "我准备上谷仓顶找乌鸦。",
            Next = 60,
            DisplayConditions = {
                { VarName = "DogStatus", VarType = "int", Op = ">=", Value = 2 },
                { VarName = "E10_ViewWhiteStone", VarType = "bool", Value = false },
                { VarName = "Chick_RoofBlockShown", VarType = "bool", Value = false }
            },
        },
        {
            Text = "我准备上谷仓顶找乌鸦。",
            Next = 60,
            DisplayConditions = {
                { VarName = "E06_LadderBorrowed", VarType = "bool", Value = true },
                { VarName = "E10_ViewWhiteStone", VarType = "bool", Value = false },
                { VarName = "Chick_RoofBlockShown", VarType = "bool", Value = false }
            },
        },
        {
            Text = "没事，走了。",
            Next = -1,
        }
    }
}

-- 提问类型（玩家需要选择回答）  -- doc:2-hub#s2#menu
-- Position: { 12300, 330 }
DialogueConfig[174] = {
    Type = "Question",
    DocTag = "2-hub#s2#menu",
    NpcName = "阿满",
    NpcSprite = "装酷",
    Dialogue = "池塘那边……你去了吗？",
    Options = {
        {
            Text = "你们到底在搞什么鬼？",
            Next = 24,
            DisplayConditions = {
                { VarName = "ChickTraceCount", VarType = "int", Op = ">=", Value = 2 },
                { VarName = "ChickStatus", VarType = "int", Op = "==", Value = 1 },
                { VarName = "BlackCat_CaseLineStarted", VarType = "bool", Value = false }
            },
        },
        {
            Text = "谷仓角落草窝，知道谁的吗？",
            Next = 45,
            DisplayConditions = {
                { VarName = "E07_ViewNapSpot", VarType = "bool", Value = true },
                { VarName = "Chick_NapSpotAsked", VarType = "bool", Value = false }
            },
        },
        {
            Text = "大黄宿醉那样，怎么叫醒？",
            Next = 51,
            DisplayConditions = {
                { VarName = "DogStatus", VarType = "int", Op = "==", Value = 2 },
                { VarName = "Chick_WakeDogHintShown", VarType = "bool", Value = false }
            },
        },
        {
            Text = "这玩意儿，你们怎么解释？",
            Next = 74,
            DisplayConditions = {
                { VarName = "E10_ViewWhiteStone", VarType = "bool", Value = true },
                { VarName = "ChickStatus", VarType = "int", Op = "<=", Value = 2 },
                { VarName = "BlackCat_CaseLineStarted", VarType = "bool", Value = false }
            },
        },
        {
            Text = "我准备上谷仓顶找乌鸦。",
            Next = 60,
            DisplayConditions = {
                { VarName = "DogStatus", VarType = "int", Op = ">=", Value = 2 },
                { VarName = "E10_ViewWhiteStone", VarType = "bool", Value = false },
                { VarName = "Chick_RoofBlockShown", VarType = "bool", Value = false }
            },
        },
        {
            Text = "我准备上谷仓顶找乌鸦。",
            Next = 60,
            DisplayConditions = {
                { VarName = "E06_LadderBorrowed", VarType = "bool", Value = true },
                { VarName = "E10_ViewWhiteStone", VarType = "bool", Value = false },
                { VarName = "Chick_RoofBlockShown", VarType = "bool", Value = false }
            },
        },
        {
            Text = "没事，走了。",
            Next = -1,
        }
    }
}

-- 提问类型（玩家需要选择回答）  -- doc:2-hub#s3#menu
-- Position: { 11950, 50 }
DialogueConfig[175] = {
    Type = "Question",
    DocTag = "2-hub#s3#menu",
    NpcName = "阿满",
    NpcSprite = "装酷",
    Dialogue = "……外勤先停了。有事就快说。",
    Options = {
        {
            Text = "你们到底在搞什么鬼？",
            Next = 24,
            DisplayConditions = {
                { VarName = "ChickTraceCount", VarType = "int", Op = ">=", Value = 2 },
                { VarName = "ChickStatus", VarType = "int", Op = "==", Value = 1 },
                { VarName = "BlackCat_CaseLineStarted", VarType = "bool", Value = false }
            },
        },
        {
            Text = "谷仓角落草窝，知道谁的吗？",
            Next = 45,
            DisplayConditions = {
                { VarName = "E07_ViewNapSpot", VarType = "bool", Value = true },
                { VarName = "Chick_NapSpotAsked", VarType = "bool", Value = false }
            },
        },
        {
            Text = "大黄宿醉那样，怎么叫醒？",
            Next = 51,
            DisplayConditions = {
                { VarName = "DogStatus", VarType = "int", Op = "==", Value = 2 },
                { VarName = "Chick_WakeDogHintShown", VarType = "bool", Value = false }
            },
        },
        {
            Text = "这玩意儿，你们怎么解释？",
            Next = 74,
            DisplayConditions = {
                { VarName = "E10_ViewWhiteStone", VarType = "bool", Value = true },
                { VarName = "ChickStatus", VarType = "int", Op = "<=", Value = 2 },
                { VarName = "BlackCat_CaseLineStarted", VarType = "bool", Value = false }
            },
        },
        {
            Text = "我准备上谷仓顶找乌鸦。",
            Next = 60,
            DisplayConditions = {
                { VarName = "DogStatus", VarType = "int", Op = ">=", Value = 2 },
                { VarName = "E10_ViewWhiteStone", VarType = "bool", Value = false },
                { VarName = "Chick_RoofBlockShown", VarType = "bool", Value = false }
            },
        },
        {
            Text = "我准备上谷仓顶找乌鸦。",
            Next = 60,
            DisplayConditions = {
                { VarName = "E06_LadderBorrowed", VarType = "bool", Value = true },
                { VarName = "E10_ViewWhiteStone", VarType = "bool", Value = false },
                { VarName = "Chick_RoofBlockShown", VarType = "bool", Value = false }
            },
        },
        {
            Text = "没事，走了。",
            Next = -1,
        }
    }
}

-- 普通对话类型  -- doc:2-hub#return@pre#1
-- Position: { 11250, 50 }
DialogueConfig[176] = {
    Type = "Normal",
    DocTag = "2-hub#return@pre#1",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（四只小鸡又挤到一起）",
    SetVariables = {
        { VarName = "Chick_HubFromSubItem", VarType = "bool", Value = false }
    },
    Next = 177  -- 下一段对话ID
}

-- 提问类型（玩家需要选择回答）  -- doc:2-hub#return#menu
-- Position: { 11600, 50 }
DialogueConfig[177] = {
    Type = "Question",
    DocTag = "2-hub#return#menu",
    NpcName = "阿满",
    NpcSprite = "装酷",
    Dialogue = "……还有什么事吗？",
    Options = {
        {
            Text = "你们到底在搞什么鬼？",
            Next = 24,
            DisplayConditions = {
                { VarName = "ChickTraceCount", VarType = "int", Op = ">=", Value = 2 },
                { VarName = "ChickStatus", VarType = "int", Op = "==", Value = 1 },
                { VarName = "BlackCat_CaseLineStarted", VarType = "bool", Value = false }
            },
        },
        {
            Text = "谷仓角落草窝，知道谁的吗？",
            Next = 45,
            DisplayConditions = {
                { VarName = "E07_ViewNapSpot", VarType = "bool", Value = true },
                { VarName = "Chick_NapSpotAsked", VarType = "bool", Value = false }
            },
        },
        {
            Text = "大黄宿醉那样，怎么叫醒？",
            Next = 51,
            DisplayConditions = {
                { VarName = "DogStatus", VarType = "int", Op = "==", Value = 2 },
                { VarName = "Chick_WakeDogHintShown", VarType = "bool", Value = false }
            },
        },
        {
            Text = "这玩意儿，你们怎么解释？",
            Next = 74,
            DisplayConditions = {
                { VarName = "E10_ViewWhiteStone", VarType = "bool", Value = true },
                { VarName = "ChickStatus", VarType = "int", Op = "<=", Value = 2 },
                { VarName = "BlackCat_CaseLineStarted", VarType = "bool", Value = false }
            },
        },
        {
            Text = "我准备上谷仓顶找乌鸦。",
            Next = 60,
            DisplayConditions = {
                { VarName = "DogStatus", VarType = "int", Op = ">=", Value = 2 },
                { VarName = "E10_ViewWhiteStone", VarType = "bool", Value = false },
                { VarName = "Chick_RoofBlockShown", VarType = "bool", Value = false }
            },
        },
        {
            Text = "我准备上谷仓顶找乌鸦。",
            Next = 60,
            DisplayConditions = {
                { VarName = "E06_LadderBorrowed", VarType = "bool", Value = true },
                { VarName = "E10_ViewWhiteStone", VarType = "bool", Value = false },
                { VarName = "Chick_RoofBlockShown", VarType = "bool", Value = false }
            },
        },
        {
            Text = "没事，走了。",
            Next = -1,
        }
    }
}

-- 普通对话类型  -- doc:2-hub#g3
-- Position: { 11600, 330 }
DialogueConfig[179] = {
    Type = "Normal",
    DocTag = "2-hub#g3",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "ChickStatus", VarType = "int", Op = "==", Value = 3, Next = 175 }
    },
    Next = 180  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-hub#g2
-- Position: { 11950, 330 }
DialogueConfig[180] = {
    Type = "Normal",
    DocTag = "2-hub#g2",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "ChickStatus", VarType = "int", Op = "==", Value = 2, Next = 174 }
    },
    Next = 181  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-hub#g1
-- Position: { 12200, 330 }
DialogueConfig[181] = {
    Type = "Normal",
    DocTag = "2-hub#g1",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "ChickStatus", VarType = "int", Op = "==", Value = 1, Next = 173 }
    },
    Next = 173  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-hub#gate
-- Position: { 11250, 330 }
DialogueConfig[182] = {
    Type = "Normal",
    DocTag = "2-hub#gate",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "Chick_HubFromSubItem", VarType = "bool", TrueNext = 176, FalseNext = 179 }
    },
    Next = 179  -- 下一段对话ID
}

-- 普通对话类型  -- doc:entry#hub
-- Position: { 1800, 150 }
DialogueConfig[183] = {
    Type = "Normal",
    DocTag = "entry#hub",
    NpcName = "小鸡们",
    NpcSprite = "装酷",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "ChickStatus", VarType = "int", Op = ">=", Value = 1, Next = 182 }
    },
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:entry#3a1
-- Position: { 1450, 150 }
DialogueConfig[184] = {
    Type = "Normal",
    DocTag = "entry#3a1",
    NpcName = "小鸡们",
    NpcSprite = "装酷",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "Chick_Chapter2GuiltShown", VarType = "bool", TrueNext = 183, FalseNext = 130 }
    },
    Next = 183  -- 下一段对话ID
}

-- 普通对话类型  -- doc:entry#3a2
-- Position: { 1100, 50 }
DialogueConfig[185] = {
    Type = "Normal",
    DocTag = "entry#3a2",
    NpcName = "小鸡们",
    NpcSprite = "装酷",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "ChickStatus", VarType = "int", Op = "==", Value = 3, Next = 184 }
    },
    Next = 183  -- 下一段对话ID
}

-- 普通对话类型  -- doc:entry#3a0
-- Position: { 750, 50 }
DialogueConfig[186] = {
    Type = "Normal",
    DocTag = "entry#3a0",
    NpcName = "小鸡们",
    NpcSprite = "装酷",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "DogStatus", VarType = "int", Op = "==", Value = 4, Next = 185 }
    },
    Next = 183  -- 下一段对话ID
}

-- 普通对话类型  -- doc:entry#2a
-- Position: { 1100, 330 }
DialogueConfig[187] = {
    Type = "Normal",
    DocTag = "entry#2a",
    NpcName = "小鸡们",
    NpcSprite = "装酷",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "ChickStatus", VarType = "int", Op = "==", Value = 0, Next = 1 }
    },
    Next = 186  -- 下一段对话ID
}

-- 普通对话类型  -- doc:entry#ng1
-- Position: { 750, 330 }
DialogueConfig[188] = {
    Type = "Normal",
    DocTag = "entry#ng1",
    NpcName = "小鸡们",
    NpcSprite = "装酷",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "Chick_NGPlusShown", VarType = "bool", TrueNext = 190, FalseNext = 131 }
    },
    Next = 190  -- 下一段对话ID
}

-- 普通对话类型  -- doc:entry#ng2
-- Position: { 400, 150 }
DialogueConfig[189] = {
    Type = "Normal",
    DocTag = "entry#ng2",
    NpcName = "小鸡们",
    NpcSprite = "装酷",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "Chick_NGPlusShown", VarType = "bool", TrueNext = 172, FalseNext = 188 }
    },
    Next = 188  -- 下一段对话ID
}

-- 普通对话类型  -- doc:entry#0
-- Position: { 50, 150 }
DialogueConfig[0] = {
    Type = "Normal",
    DocTag = "entry#0",
    NpcName = "小鸡们",
    NpcSprite = "装酷",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "NGPlus", VarType = "bool", TrueNext = 189, FalseNext = 190 }
    },
    Next = 190  -- 下一段对话ID
}

-- entry#2g · BlackCat_CaseLineStarted && ChickStatus<=1 → 2-G
DialogueConfig[190] = {
    Type = "Normal",
    DocTag = "entry#2g",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "BlackCat_CaseLineStarted", VarType = "bool", TrueNext = 191, FalseNext = 187 }
    },
    Next = 187
}

DialogueConfig[191] = {
    Type = "Normal",
    DocTag = "entry#2g-status",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "ChickStatus", VarType = "int", Op = "<=", Value = 1, Next = 200 }
    },
    Next = 187
}

-- ==================== 2-G · 黑猫案情补漏全招 ====================

DialogueConfig[200] = {
    Type = "Normal",
    DocTag = "2-G#1",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "黑猫让我来问——你们这两天到底发生了什么？我在乌鸦那儿看见一块白石头，跟你们有关吧。",
    Next = 201
}

DialogueConfig[201] = {
    Type = "Normal",
    DocTag = "2-G#2",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（四只小鸡僵住）",
    Next = 202
}

DialogueConfig[202] = {
    Type = "Normal",
    DocTag = "2-G#3",
    NpcName = "阿满",
    NpcSprite = "心虚",
    Dialogue = "……",
    Next = 203
}

DialogueConfig[203] = {
    Type = "Normal",
    DocTag = "2-G#4",
    NpcName = "瓜子",
    NpcSprite = "心虚",
    Dialogue = "（哭腔）我们……我们把弟弟弄丢了……",
    Next = 204
}

DialogueConfig[204] = {
    Type = "Normal",
    DocTag = "2-G#5",
    NpcName = "阿满",
    NpcSprite = "愧疚",
    Dialogue = "大前天下午，我们捡了块白石头，画成蛋的样子，放进窝里假装是蛋，",
    Next = 217
}

DialogueConfig[217] = {
    Type = "Normal",
    DocTag = "2-G#5b",
    NpcName = "阿满",
    NpcSprite = "愧疚",
    Dialogue = "然后把真的弟弟偷出来——踢球。",
    Next = 205
}

DialogueConfig[205] = {
    Type = "Normal",
    DocTag = "2-G#6",
    NpcName = "阿满",
    NpcSprite = "愧疚",
    Dialogue = "推着弟弟路过谷仓时，老鼠叔叔蹿出来说——",
    Next = 218
}

DialogueConfig[218] = {
    Type = "Normal",
    DocTag = "2-G#6b",
    NpcName = "阿满",
    NpcSprite = "愧疚",
    Dialogue = "有沼泽水怪，专门吃沾泥的蛋！",
    Next = 206
}

DialogueConfig[206] = {
    Type = "Normal",
    DocTag = "2-G#7",
    NpcName = "豆豆",
    NpcSprite = "心虚",
    Dialogue = "（气鼓鼓）现在想起来他们全程在憋笑！！",
    Next = 207
}

DialogueConfig[207] = {
    Type = "Normal",
    DocTag = "2-G#8",
    NpcName = "玩家",
    NpcSprite = "惊讶",
    Dialogue = "然后呢？",
    Next = 219
}

DialogueConfig[219] = {
    Type = "Normal",
    DocTag = "2-G#8b",
    NpcName = "阿满",
    NpcSprite = "愧疚",
    Dialogue = "我们吓得跑去池塘洗蛋，又被青蛙的话吓着了——",
    Next = 208
}

DialogueConfig[208] = {
    Type = "Normal",
    DocTag = "2-G#9",
    NpcName = "阿满",
    NpcSprite = "愧疚",
    Dialogue = "赶紧把真蛋推回窝里！",
    Next = 209
}

DialogueConfig[209] = {
    Type = "Normal",
    DocTag = "2-G#10",
    NpcName = "米粒",
    NpcSprite = "愧疚",
    Dialogue = "假石头嘛……大前天随手扔进草丛了……",
    Next = 210
}

DialogueConfig[210] = {
    Type = "Normal",
    DocTag = "2-G#11",
    NpcName = "瓜子",
    NpcSprite = "心虚",
    Dialogue = "（小声）后来……被乌鸦叼走了。",
    Next = 211
}

DialogueConfig[211] = {
    Type = "Normal",
    DocTag = "2-G#12",
    NpcName = "阿满",
    NpcSprite = "愧疚",
    Dialogue = "弟弟当时已经推回窝了。真要不见，是昨晚！",
    Next = 212
}

DialogueConfig[212] = {
    Type = "Normal",
    DocTag = "2-G#13",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "昨晚有动静吗？",
    Next = 213
}

DialogueConfig[213] = {
    Type = "Normal",
    DocTag = "2-G#14",
    NpcName = "豆豆",
    NpcSprite = "愧疚",
    Dialogue = "睡前弟弟还在……半夜一看，窝空了……",
    Next = 214
}

DialogueConfig[214] = {
    Type = "Normal",
    DocTag = "2-G#15",
    NpcName = "米粒",
    NpcSprite = "心虚",
    Dialogue = "外面有好响的声音……我们以为是水怪……",
    Next = 215
}

DialogueConfig[215] = {
    Type = "Normal",
    DocTag = "2-G#16",
    NpcName = "阿满",
    NpcSprite = "愧疚",
    Dialogue = "（哭）如果没有水怪……到底是谁带走了弟弟？",
    Next = 216
}

DialogueConfig[216] = {
    Type = "Normal",
    DocTag = "2-G#17",
    NpcName = "米粒",
    NpcSprite = "心虚",
    Dialogue = "昨晚那声响……青蛙说不定听见了。去问问他……求你……",
    SetVariables = {
        { VarName = "ChickStatus", VarType = "int", Value = 3 },
        { VarName = "Chick_HubFromSubItem", VarType = "bool", Value = true },
    },
    Next = 182
}
