-- 对话配置文件
-- Generated by doc_to_lua.py (Phase 2 — do not overwrite production files)
-- Scene DialogueTrigger start ID should be 0 (entry dispatcher)
-- doc node map:
--   __entry__ -> DialogueConfig[0]
--   1-A -> DialogueConfig[1]
--   1-A' -> DialogueConfig[14]
--   1-B -> DialogueConfig[15]
--   1-C -> DialogueConfig[23]
--   1-D -> DialogueConfig[29]
--   1-E -> DialogueConfig[30]
--   1-F -> DialogueConfig[36]
--   1-G -> DialogueConfig[41]
--   2-A -> DialogueConfig[58]
--   2-hub#menu -> DialogueConfig[61]
--   2-hub -> DialogueConfig[62]
--   2-A' -> DialogueConfig[63]
--   2-B -> DialogueConfig[65]
--   2-C -> DialogueConfig[92]
--   2-E -> DialogueConfig[93]
--   NGPlus -> DialogueConfig[107]

DialogueConfig = {}

-- 普通对话类型  -- doc:entry#0
-- Position: { 50, 150 }
DialogueConfig[0] = {
    Type = "Normal",
    DocTag = "entry#0",
    NpcName = "大黄",
    NpcSprite = "",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "NGPlus", VarType = "bool", TrueNext = 107, FalseNext = 121 }
    },
    Next = 121  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-A#1
-- Position: { 50, 1550 }
DialogueConfig[1] = {
    Type = "Normal",
    DocTag = "1-A#1",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（谷仓墙根旁，一架短木梯侧倒在地，",
    Next = 820
}

DialogueConfig[820] = {
    Type = "Normal",
    DocTag = "1-A#1b",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "一只黄毛大狗半压在上面，低沉的鼾声带着哨音）",
    Next = 2
}

-- 普通对话类型  -- doc:1-A#2
-- Position: { 400, 1550 }
DialogueConfig[2] = {
    Type = "Normal",
    DocTag = "1-A#2",
    NpcName = "大黄",
    NpcSprite = "醉倒",
    Dialogue = "嗝——",
    Next = 3  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-A#3
-- Position: { 750, 1550 }
DialogueConfig[3] = {
    Type = "Normal",
    DocTag = "1-A#3",
    NpcName = "大黄",
    NpcSprite = "醉倒",
    Dialogue = "谁……",
    Next = 4  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-A#4
-- Position: { 1100, 1550 }
DialogueConfig[4] = {
    Type = "Normal",
    DocTag = "1-A#4",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "淑芬的蛋不见了。你看到过什么吗？",
    Next = 5  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-A#5
-- Position: { 1450, 1550 }
DialogueConfig[5] = {
    Type = "Normal",
    DocTag = "1-A#5",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（大黄的耳朵动了一下，目光慢慢聚过来）",
    Next = 6  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-A#6
-- Position: { 1800, 1550 }
DialogueConfig[6] = {
    Type = "Normal",
    DocTag = "1-A#6",
    NpcName = "大黄",
    NpcSprite = "醉倒",
    Dialogue = "蛋……乌鸦……叼走了。",
    Next = 7  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-A#7
-- Position: { 2150, 1550 }
DialogueConfig[7] = {
    Type = "Normal",
    DocTag = "1-A#7",
    NpcName = "玩家",
    NpcSprite = "惊讶",
    Dialogue = "乌鸦？",
    Next = 8  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-A#8
-- Position: { 2500, 1550 }
DialogueConfig[8] = {
    Type = "Normal",
    DocTag = "1-A#8",
    NpcName = "大黄",
    NpcSprite = "醉倒",
    Dialogue = "嗯……乌鸦往谷仓屋顶飞了。我追了，跳不上去，就咬到一嘴空气。",
    Next = 9  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-A#9
-- Position: { 2850, 1550 }
DialogueConfig[9] = {
    Type = "Normal",
    DocTag = "1-A#9",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（大黄把脑袋重新压回前爪上，声音低下去）",
    Next = 10  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-A#10
-- Position: { 3200, 1550 }
DialogueConfig[10] = {
    Type = "Normal",
    DocTag = "1-A#10",
    NpcName = "大黄",
    NpcSprite = "醉倒",
    Dialogue = "我失职了……没护住淑芬的蛋。",
    SetVariables = {
        { VarName = "DogStatus", VarType = "int", Value = 2 }
    },
    ConditionBranches = {
        { VarName = "E06_ViewNeedLadder", VarType = "bool", TrueNext = 11, FalseNext = 14 }
    },
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-A@cond#1
-- Position: { 3550, 1550 }
DialogueConfig[11] = {
    Type = "Normal",
    DocTag = "1-A@cond#1",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "你身下压着一架短木梯，能先挪一下吗？",
    Next = 821
}

DialogueConfig[821] = {
    Type = "Normal",
    DocTag = "1-A@cond#1b",
    NpcName = "玩家",
    NpcSprite = "正常",
    Dialogue = "谷仓入口那道矮墙翻不过去。",
    Next = 12
}

-- 普通对话类型  -- doc:1-A@cond#2
-- Position: { 3900, 1550 }
DialogueConfig[12] = {
    Type = "Normal",
    DocTag = "1-A@cond#2",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（大黄迷迷糊糊蹬了下腿，短梯反而被压得更实）",
    Next = 13  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-A@cond#3
-- Position: { 4250, 1550 }
DialogueConfig[13] = {
    Type = "Normal",
    DocTag = "1-A@cond#3",
    NpcName = "大黄",
    NpcSprite = "醉倒",
    Dialogue = "……别推……",
    Next = 14  -- 下一段对话ID
}

-- 提问类型（玩家需要选择回答）  -- doc:1-A'
-- Position: { 4700, 1550 }
DialogueConfig[14] = {
    Type = "Question",
    DocTag = "1-A'",
    NpcName = "大黄",
    NpcSprite = "醉倒",
    Dialogue = "嗝……",
    Options = {
        {
            Text = "大黄，先喝点这个。",
            Next = 15,
            DisplayConditions = {
                { VarName = "E05_GrainSoakGet", VarType = "bool", Value = true }
            },
        },
        {
            Text = "大黄，醒醒。",
            Next = 23,
            DisplayConditions = {
                { VarName = "E05_GrainSoakGet", VarType = "bool", Value = false }
            },
        },
        {
            Text = "我等会回来。",
            Next = -1,
        }
    }
}

-- 普通对话类型  -- doc:1-B#1
-- Position: { 5150, 1550 }
DialogueConfig[15] = {
    Type = "Normal",
    DocTag = "1-B#1",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "大黄，先喝点这个。",
    Next = 16  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-B#2
-- Position: { 5500, 1550 }
DialogueConfig[16] = {
    Type = "Normal",
    DocTag = "1-B#2",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（大黄眯着眼凑近闻了闻，探出舌头慢慢吮着喝，中途顿了顿，又埋头接着喝）",
    Next = 17  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-B#3
-- Position: { 5850, 1550 }
DialogueConfig[17] = {
    Type = "Normal",
    DocTag = "1-B#3",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（片刻后，大黄猛地甩了下脑袋——湿树叶从额头飞出去）",
    Next = 18  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-B#4
-- Position: { 6200, 1550 }
DialogueConfig[18] = {
    Type = "Normal",
    DocTag = "1-B#4",
    NpcName = "大黄",
    NpcSprite = "醉倒",
    Dialogue = "呕——",
    Next = 19  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-B#5
-- Position: { 6550, 1550 }
DialogueConfig[19] = {
    Type = "Normal",
    DocTag = "1-B#5",
    NpcName = "大黄",
    NpcSprite = "醉倒",
    Dialogue = "嗝——",
    Next = 20  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-B#6
-- Position: { 6900, 1550 }
DialogueConfig[20] = {
    Type = "Normal",
    DocTag = "1-B#6",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（大黄使劲眨眼，目光开始聚焦）",
    Next = 21  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-B#7
-- Position: { 7250, 1550 }
DialogueConfig[21] = {
    Type = "Normal",
    DocTag = "1-B#7",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（四肢从梯子上撑起来，摇摇晃晃站稳）",
    Next = 22  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-B#8
-- Position: { 7600, 1550 }
DialogueConfig[22] = {
    Type = "Normal",
    DocTag = "1-B#8",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "……嗯，清楚多了。",
    SetVariables = {
        { VarName = "DogStatus", VarType = "int", Value = 3 }
    },
    Next = 29  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-C#1
-- Position: { 50, 2000 }
DialogueConfig[23] = {
    Type = "Normal",
    DocTag = "1-C#1",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "大黄，醒醒。",
    Next = 24  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-C#2
-- Position: { 400, 2100 }
DialogueConfig[24] = {
    Type = "Normal",
    DocTag = "1-C#2",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（大黄哼了一声，把头埋进前爪里）",
    Next = 25  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-C#3
-- Position: { 750, 2100 }
DialogueConfig[25] = {
    Type = "Normal",
    DocTag = "1-C#3",
    NpcName = "大黄",
    NpcSprite = "醉倒",
    Dialogue = "嗝……别吵……",
    ConditionBranches = {
        { VarName = "E06_ViewNeedLadder", VarType = "bool", TrueNext = 28, FalseNext = 27 }
    },
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-C@cond#1
-- Position: { 50, 2280 }
DialogueConfig[26] = {
    Type = "Normal",
    DocTag = "1-C@cond#1",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "这样叫不醒。得找点能让他清醒的东西。",
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-C@a#1
-- Position: { 1100, 2000 }
DialogueConfig[27] = {
    Type = "Normal",
    DocTag = "1-C@a#1",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "这样叫不醒。得找点能让他清醒的东西。",
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-C@b#1
-- Position: { 1100, 2280 }
DialogueConfig[28] = {
    Type = "Normal",
    DocTag = "1-C@b#1",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "这样叫不醒。得先让他清醒过来，短梯才借得出来。",
    Next = -1  -- 下一段对话ID
}

-- 提问类型（玩家需要选择回答）  -- doc:1-D
-- Position: { 1550, 2100 }
DialogueConfig[29] = {
    Type = "Question",
    DocTag = "1-D",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "你还有什么事吗？",
    Options = {
        {
            Text = "梯子能借我吗？",
            Next = 30,
            DisplayConditions = {
                { VarName = "E06_ViewNeedLadder", VarType = "bool", Value = true },
                { VarName = "E06_LadderBorrowed", VarType = "bool", Value = false }
            },
        },
        {
            Text = "谷仓那草窝是谁的？",
            Next = 36,
            DisplayConditions = {
                { VarName = "E07_ViewNapSpot", VarType = "bool", Value = true },
                { VarName = "E07_NapSpotAsked", VarType = "bool", Value = false }
            },
        },
        {
            Text = "这是你追的蛋吗？",
            Next = 41,
            DisplayConditions = {
                { VarName = "E10_ViewWhiteStone", VarType = "bool", Value = true }
            },
        },
        {
            Text = "目前没什么事了。",
            Next = -1,
        }
    }
}

-- 普通对话类型  -- doc:1-E#1
-- Position: { 2000, 2100 }
DialogueConfig[30] = {
    Type = "Normal",
    DocTag = "1-E#1",
    NpcName = "玩家",
    NpcSprite = "正常",
    Dialogue = "大黄，梯子能借我吗？入口那道小围墙，我得翻过去。",
    Next = 31  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-E#2
-- Position: { 2350, 2100 }
DialogueConfig[31] = {
    Type = "Normal",
    DocTag = "1-E#2",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "梯子？",
    Next = 32  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-E#3
-- Position: { 2700, 2100 }
DialogueConfig[32] = {
    Type = "Normal",
    DocTag = "1-E#3",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（大黄扭头看向身侧那架侧倒的木梯）",
    Next = 33  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-E#4
-- Position: { 3050, 2100 }
DialogueConfig[33] = {
    Type = "Normal",
    DocTag = "1-E#4",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "哦。对哦。拿去吧。",
    Next = 34  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-E#5
-- Position: { 3400, 2100 }
DialogueConfig[34] = {
    Type = "Normal",
    DocTag = "1-E#5",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（大黄用前爪把木梯往这边推了推）",
    Next = 35  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-E#6
-- Position: { 3750, 2100 }
DialogueConfig[35] = {
    Type = "Normal",
    DocTag = "1-E#6",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "架稳了再翻。别摔着。",
    SetVariables = {
        { VarName = "E06_LadderBorrowed", VarType = "bool", Value = true }
    },
    ConditionBranches = {
        { VarName = "DogStatus", VarType = "int", Op = "==", Value = 3, Next = 29 }
    },
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-F#1
-- Position: { 50, 2830 }
DialogueConfig[36] = {
    Type = "Normal",
    DocTag = "1-F#1",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "谷仓角落有一片被压扁的草窝，你知道是哪个动物的吗？",
    Next = 37  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-F#2
-- Position: { 400, 2830 }
DialogueConfig[37] = {
    Type = "Normal",
    DocTag = "1-F#2",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "谷仓角落那个草窝？",
    Next = 38  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-F#3
-- Position: { 750, 2830 }
DialogueConfig[38] = {
    Type = "Normal",
    DocTag = "1-F#3",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（大黄皱起眉头，努力回想）",
    Next = 39  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-F#4
-- Position: { 1100, 2830 }
DialogueConfig[39] = {
    Type = "Normal",
    DocTag = "1-F#4",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "前两天好像瞥见两个灰乎乎的小东西窜过去，太快了，没看清。",
    Next = 40  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-F#5
-- Position: { 1450, 2830 }
DialogueConfig[40] = {
    Type = "Normal",
    DocTag = "1-F#5",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "也可能是我那两天喝糊涂了。",
    SetVariables = {
        { VarName = "E07_NapSpotAsked", VarType = "bool", Value = true }
    },
    ConditionBranches = {
        { VarName = "DogStatus", VarType = "int", Op = "==", Value = 3, Next = 29 },
        { VarName = "DogStatus", VarType = "int", Op = "==", Value = 4, Next = 62 }
    },
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-G#1
-- Position: { 1900, 2830 }
DialogueConfig[41] = {
    Type = "Normal",
    DocTag = "1-G#1",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "大黄，你看这个——是不是你那天追的蛋？",
    Next = 42  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-G#2
-- Position: { 2250, 2830 }
DialogueConfig[42] = {
    Type = "Normal",
    DocTag = "1-G#2",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（大黄低头凑近，仔细盯着摊开的笔记本）",
    Next = 43  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-G#3
-- Position: { 2600, 2830 }
DialogueConfig[43] = {
    Type = "Normal",
    DocTag = "1-G#3",
    NpcName = "大黄",
    NpcSprite = "振奋",
    Dialogue = "这是……什么？",
    Next = 44  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-G#4
-- Position: { 2950, 2830 }
DialogueConfig[44] = {
    Type = "Normal",
    DocTag = "1-G#4",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（大黄眼睛睁大，头伸得更近）",
    Next = 45  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-G#5
-- Position: { 3300, 2830 }
DialogueConfig[45] = {
    Type = "Normal",
    DocTag = "1-G#5",
    NpcName = "大黄",
    NpcSprite = "振奋",
    Dialogue = "一块石头？",
    Next = 46  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-G#6
-- Position: { 3650, 2830 }
DialogueConfig[46] = {
    Type = "Normal",
    DocTag = "1-G#6",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（大黄抬起脑袋，僵在那里）",
    Next = 47  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-G#7
-- Position: { 4000, 2830 }
DialogueConfig[47] = {
    Type = "Normal",
    DocTag = "1-G#7",
    NpcName = "大黄",
    NpcSprite = "振奋",
    Dialogue = "……跟乌鸦叼走那玩意儿，形状差不多。",
    Next = 48  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-G#8
-- Position: { 4350, 2830 }
DialogueConfig[48] = {
    Type = "Normal",
    DocTag = "1-G#8",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "乌鸦一直守着这块石头，说是他的部落图腾宝石。",
    Next = 49  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-G#9
-- Position: { 4700, 2830 }
DialogueConfig[49] = {
    Type = "Normal",
    DocTag = "1-G#9",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（大黄盯着笔记本，一动不动）",
    Next = 50  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-G#10
-- Position: { 5050, 2830 }
DialogueConfig[50] = {
    Type = "Normal",
    DocTag = "1-G#10",
    NpcName = "大黄",
    NpcSprite = "振奋",
    Dialogue = "所以乌鸦叼走的……不是淑芬的蛋？",
    Next = 51  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-G#11
-- Position: { 5400, 2830 }
DialogueConfig[51] = {
    Type = "Normal",
    DocTag = "1-G#11",
    NpcName = "大黄",
    NpcSprite = "振奋",
    Dialogue = "……我——",
    Next = 52  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-G#12
-- Position: { 5750, 2830 }
DialogueConfig[52] = {
    Type = "Normal",
    DocTag = "1-G#12",
    NpcName = "大黄",
    NpcSprite = "振奋",
    Dialogue = "那我不是废柴保安！",
    Next = 53  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-G#13
-- Position: { 6100, 2830 }
DialogueConfig[53] = {
    Type = "Normal",
    DocTag = "1-G#13",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（尾巴猛地甩动起来，停不下来）",
    Next = 54  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-G#14
-- Position: { 6450, 2830 }
DialogueConfig[54] = {
    Type = "Normal",
    DocTag = "1-G#14",
    NpcName = "大黄",
    NpcSprite = "振奋",
    Dialogue = "淑芬的蛋一定还在！",
    Next = 55  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-G#15
-- Position: { 6800, 2830 }
DialogueConfig[55] = {
    Type = "Normal",
    DocTag = "1-G#15",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（大黄一个激灵，深吸一口气）",
    Next = 56  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-G#16
-- Position: { 7150, 2830 }
DialogueConfig[56] = {
    Type = "Normal",
    DocTag = "1-G#16",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（在某个方向停下来，神情郑重）",
    Next = 57  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-G#17
-- Position: { 7500, 2830 }
DialogueConfig[57] = {
    Type = "Normal",
    DocTag = "1-G#17",
    NpcName = "大黄",
    NpcSprite = "振奋",
    Dialogue = "蛋的气味在那边——红顶屋那一片。主人住的那栋，过了桥就到。",
    Next = 826  -- 下一段对话ID
}

DialogueConfig[826] = {
    Type = "Normal",
    DocTag = "1-G#17b",
    NpcName = "大黄",
    NpcSprite = "振奋",
    Dialogue = "我先走一步，桥那边见！",
    SetVariables = {
        { VarName = "DogStatus", VarType = "int", Value = 4 }
    },
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#1
-- Position: { 8900, 150 }
DialogueConfig[58] = {
    Type = "Normal",
    DocTag = "2-A#1",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（大黄在红顶屋外站定，尾巴轻轻绷着）",
    Next = 59  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#2
-- Position: { 9250, 150 }
DialogueConfig[59] = {
    Type = "Normal",
    DocTag = "2-A#2",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "就是这儿。",
    SetVariables = {
        { VarName = "RedRoof_IntroShown", VarType = "bool", Value = true }
    },
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-hub!E13#1
-- Position: { 10050, 50 }
DialogueConfig[60] = {
    Type = "Normal",
    DocTag = "2-hub!E13#1",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "你先去看看那扇门。",
    Next = -1  -- 下一段对话ID
}

-- 提问类型（玩家需要选择回答）  -- doc:2-hub#menu
-- Position: { 10050, 330 }
DialogueConfig[61] = {
    Type = "Question",
    DocTag = "2-hub#menu",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "查到什么了吗？",
    Options = {
        {
            Text = "正门进不去。",
            Next = 63,
            DisplayConditions = {
                { VarName = "E13_ViewDoorBlocked", VarType = "bool", Value = true },
                { VarName = "RedRoof_DoorHintShown", VarType = "bool", Value = false }
            },
        },
        {
            Text = "红屋顶里还住着别的动物？",
            Next = 65,
            DisplayConditions = {
                { VarName = "E13_ViewDoorBlocked", VarType = "bool", Value = true },
                { VarName = "TreeClueCount", VarType = "int", Op = ">=", Value = 2 },
                { VarName = "Dog_BlackCatSummoned", VarType = "bool", Value = false }
            },
        },
        {
            Text = "谷仓那草窝是谁的？",
            Next = 36,
            DisplayConditions = {
                { VarName = "E07_ViewNapSpot", VarType = "bool", Value = true },
                { VarName = "E07_NapSpotAsked", VarType = "bool", Value = false }
            },
        },
        {
            Text = "目前没查到什么。",
            Next = -1,
        }
    }
}

-- 普通对话类型  -- doc:2-hub#gate
-- Position: { 9700, 150 }
DialogueConfig[62] = {
    Type = "Normal",
    DocTag = "2-hub#gate",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "E13_ViewDoorBlocked", VarType = "bool", TrueNext = 61, FalseNext = 60 }
    },
    Next = 60  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A'#1
-- Position: { 10500, 150 }
DialogueConfig[63] = {
    Type = "Normal",
    DocTag = "2-A'#1",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "正门进不去。",
    Next = 64  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A'#2
-- Position: { 10850, 150 }
DialogueConfig[64] = {
    Type = "Normal",
    DocTag = "2-A'#2",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "……那怎么办啊。侦探，你再看看，我待会儿也试试。",
    SetVariables = {
        { VarName = "RedRoof_DoorHintShown", VarType = "bool", Value = true }
    },
    Next = 62  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-B#1
-- Position: { 8900, 880 }
DialogueConfig[65] = {
    Type = "Normal",
    DocTag = "2-B#1",
    NpcName = "玩家",
    NpcSprite = "正常",
    Dialogue = "这里有一扇精美的小门，还有一撮动物的毛，",
    Next = 822
}

DialogueConfig[822] = {
    Type = "Normal",
    DocTag = "2-B#1b",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "红屋顶里还住着别的动物？",
    SetVariables = {
        { VarName = "BlackCat_TreeShakeStarted", VarType = "bool", Value = true }
    },
    Next = 66
}

-- 普通对话类型  -- doc:2-B#2
-- Position: { 9250, 880 }
DialogueConfig[66] = {
    Type = "Normal",
    DocTag = "2-B#2",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（大黄愣了一下，猛地用爪子拍了下自己脑门）",
    Next = 67  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-B#3
-- Position: { 9600, 880 }
DialogueConfig[67] = {
    Type = "Normal",
    DocTag = "2-B#3",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "哎哟！我这狗脑子，准是酒还没醒透！",
    Next = 68  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-B#4
-- Position: { 9950, 880 }
DialogueConfig[68] = {
    Type = "Normal",
    DocTag = "2-B#4",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "你想起什么了？",
    Next = 69  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-B#5
-- Position: { 10300, 880 }
DialogueConfig[69] = {
    Type = "Normal",
    DocTag = "2-B#5",
    NpcName = "大黄",
    NpcSprite = "振奋",
    Dialogue = "有只猫！那只傲慢的黑猫！",
    Next = 823
}

DialogueConfig[823] = {
    Type = "Normal",
    DocTag = "2-B#5b",
    NpcName = "大黄",
    NpcSprite = "振奋",
    Dialogue = "他有专属猫门，钥匙就挂脖子上！",
    Next = 70
}

-- 普通对话类型  -- doc:2-B#6
-- Position: { 10650, 880 }
DialogueConfig[70] = {
    Type = "Normal",
    DocTag = "2-B#6",
    NpcName = "玩家",
    NpcSprite = "惊讶",
    Dialogue = "他在哪儿？",
    Next = 71  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-B#7
-- Position: { 11000, 880 }
DialogueConfig[71] = {
    Type = "Normal",
    DocTag = "2-B#7",
    NpcName = "大黄",
    NpcSprite = "振奋",
    Dialogue = "大橡树上！",
    Next = 72  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-B#8
-- Position: { 11350, 880 }
DialogueConfig[72] = {
    Type = "Normal",
    DocTag = "2-B#8",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（双爪抵住树干，猛地摇晃）",
    Next = 73  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-B#9
-- Position: { 11700, 880 }
DialogueConfig[73] = {
    Type = "Normal",
    DocTag = "2-B#9",
    NpcName = "大黄",
    NpcSprite = "振奋",
    Dialogue = "猫大爷！下来！这事儿得你出马！",
    UnlockBranches = {
        { NpcName = "黑猫", BranchId = 1 }
    },
    ChainDialogue = { NpcName = "黑猫", StartId = 1 },
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-C@v1#1
-- Position: { 12150, 780 }
DialogueConfig[74] = {
    Type = "Normal",
    DocTag = "2-C@v1#1",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "大黄，你认识那只黑猫很久了吗？",
    Next = 75  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-C@v1#2
-- Position: { 12500, 780 }
DialogueConfig[75] = {
    Type = "Normal",
    DocTag = "2-C@v1#2",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "挺久的。他刚来的时候……比我一只爪子还小。",
    Next = 76  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-C@v1#3
-- Position: { 12850, 780 }
DialogueConfig[76] = {
    Type = "Normal",
    DocTag = "2-C@v1#3",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（大黄往下看了看自己的爪子）",
    Next = 77  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-C@v1#4
-- Position: { 13200, 780 }
DialogueConfig[77] = {
    Type = "Normal",
    DocTag = "2-C@v1#4",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "那会儿什么都不懂，连怎么爬树都不会。我教过他一次。",
    Next = 78  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-C@v1#5
-- Position: { 13550, 780 }
DialogueConfig[78] = {
    Type = "Normal",
    DocTag = "2-C@v1#5",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "他学会了吗？",
    Next = 79  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-C@v1#6
-- Position: { 13900, 780 }
DialogueConfig[79] = {
    Type = "Normal",
    DocTag = "2-C@v1#6",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "学会了。后来他就不理我了。",
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-C@v2#1
-- Position: { 12150, 1060 }
DialogueConfig[80] = {
    Type = "Normal",
    DocTag = "2-C@v2#1",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "他小时候怕什么吗？",
    Next = 81  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-C@v2#2
-- Position: { 12500, 1060 }
DialogueConfig[81] = {
    Type = "Normal",
    DocTag = "2-C@v2#2",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "怕下雨。",
    Next = 810  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-C@v2#2b
-- Position: { 12600, 1060 }
DialogueConfig[810] = {
    Type = "Normal",
    DocTag = "2-C@v2#2b",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "每次打雷，他就跑来我狗窝旁边蹲着。",
    Next = 811  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-C@v2#2c
-- Position: { 12700, 1060 }
DialogueConfig[811] = {
    Type = "Normal",
    DocTag = "2-C@v2#2c",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "我说进来吧，他说本喵只是路过，",
    Next = 824
}

DialogueConfig[824] = {
    Type = "Normal",
    DocTag = "2-C@v2#2d",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "然后在门口站了整整一夜。",
    Next = 82
}

-- 普通对话类型  -- doc:2-C@v2#3
-- Position: { 12850, 1060 }
DialogueConfig[82] = {
    Type = "Normal",
    DocTag = "2-C@v2#3",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（大黄挠挠耳朵）",
    Next = 83  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-C@v2#4
-- Position: { 13200, 1060 }
DialogueConfig[83] = {
    Type = "Normal",
    DocTag = "2-C@v2#4",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "我后来提过一次，他说从来没进过我狗窝、那种地方。",
    Next = 825
}

DialogueConfig[825] = {
    Type = "Normal",
    DocTag = "2-C@v2#4b",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "他就这脾气，嘴硬得很。",
    Next = -1
}

-- 普通对话类型  -- doc:2-C@v3#1
-- Position: { 12150, 1340 }
DialogueConfig[84] = {
    Type = "Normal",
    DocTag = "2-C@v3#1",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（大黄看着黑猫蹲着的方向）",
    Next = 85  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-C@v3#2
-- Position: { 12500, 1340 }
DialogueConfig[85] = {
    Type = "Normal",
    DocTag = "2-C@v3#2",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "他还在。",
    Next = 86  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-C@v3#3
-- Position: { 12850, 1340 }
DialogueConfig[86] = {
    Type = "Normal",
    DocTag = "2-C@v3#3",
    NpcName = "玩家",
    NpcSprite = "惊讶",
    Dialogue = "什么？",
    Next = 87  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-C@v3#4
-- Position: { 13200, 1340 }
DialogueConfig[87] = {
    Type = "Normal",
    DocTag = "2-C@v3#4",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "我说，他还没走。换别的猫，被人从树上晃下来，早溜了。",
    Next = 88  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-C@v3#5
-- Position: { 13550, 1060 }
DialogueConfig[88] = {
    Type = "Normal",
    DocTag = "2-C@v3#5",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（大黄若无其事地往旁边挪了半步）",
    Next = 89  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-C@v3#6
-- Position: { 13900, 1060 }
DialogueConfig[89] = {
    Type = "Normal",
    DocTag = "2-C@v3#6",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "他在听呢。就是不想让人看出来。",
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-C@v4#1
-- Position: { 12150, 1620 }
DialogueConfig[90] = {
    Type = "Normal",
    DocTag = "2-C@v4#1",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（大黄坐在橡树旁，望向红顶屋方向）",
    Next = 91  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-C@v4#2
-- Position: { 12500, 1620 }
DialogueConfig[91] = {
    Type = "Normal",
    DocTag = "2-C@v4#2",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "我守着。",
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-C
-- Position: { 12150, 1900 }
DialogueConfig[92] = {
    Type = "Normal",
    DocTag = "2-C",
    NpcName = "大黄",
    NpcSprite = "",
    Dialogue = "",
    RotatePool = { 74, 80, 84, 90 },
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#1
-- Position: { 14350, 880 }
DialogueConfig[93] = {
    Type = "Normal",
    DocTag = "2-E#1",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（大黄仰头看向红顶屋屋顶，尾巴轻轻摇着）",
    Next = 94  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-E#2
-- Position: { 14700, 880 }
DialogueConfig[94] = {
    Type = "Normal",
    DocTag = "2-E#2",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "加油。我守在这儿等着。",
    SetVariables = {
        { VarName = "RedRoof_RoofWaitShown", VarType = "bool", Value = true }
    },
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus@v1#1
-- Position: { 8900, 3200 }
DialogueConfig[95] = {
    Type = "Normal",
    DocTag = "NGPlus@v1#1",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "巡逻中。一切正常。",
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus@v2#1
-- Position: { 8900, 3480 }
DialogueConfig[96] = {
    Type = "Normal",
    DocTag = "NGPlus@v2#1",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "大黄，那块石头最后怎么了？",
    Next = 97  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus@v2#2
-- Position: { 9250, 3200 }
DialogueConfig[97] = {
    Type = "Normal",
    DocTag = "NGPlus@v2#2",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "还在乌鸦那儿。我问过，它说是部落图腾宝石，了不得。",
    Next = 98  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus@v2#3
-- Position: { 9600, 3200 }
DialogueConfig[98] = {
    Type = "Normal",
    DocTag = "NGPlus@v2#3",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（大黄挠了挠耳朵）",
    Next = 99  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus@v2#4
-- Position: { 9950, 3200 }
DialogueConfig[99] = {
    Type = "Normal",
    DocTag = "NGPlus@v2#4",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "……随它去吧。",
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus@v3#1
-- Position: { 8900, 3760 }
DialogueConfig[100] = {
    Type = "Normal",
    DocTag = "NGPlus@v3#1",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "我想……下次再碰见苹果渣，不喝了。",
    Next = 101  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus@v3#2
-- Position: { 9250, 3480 }
DialogueConfig[101] = {
    Type = "Normal",
    DocTag = "NGPlus@v3#2",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（停顿）",
    Next = 102  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus@v3#3
-- Position: { 9600, 3480 }
DialogueConfig[102] = {
    Type = "Normal",
    DocTag = "NGPlus@v3#3",
    NpcName = "大黄",
    NpcSprite = "振奋",
    Dialogue = "我是保安。不是酒鬼。",
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus@v4#1
-- Position: { 8900, 4040 }
DialogueConfig[103] = {
    Type = "Normal",
    DocTag = "NGPlus@v4#1",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "大黄，以后还会有蛋失踪吗？",
    Next = 104  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus@v4#2
-- Position: { 9250, 3760 }
DialogueConfig[104] = {
    Type = "Normal",
    DocTag = "NGPlus@v4#2",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "不会了。",
    Next = 105  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus@v4#3
-- Position: { 9600, 3760 }
DialogueConfig[105] = {
    Type = "Normal",
    DocTag = "NGPlus@v4#3",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（大黄低头看了看项圈，抬头）",
    Next = 106  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus@v4#4
-- Position: { 9950, 3480 }
DialogueConfig[106] = {
    Type = "Normal",
    DocTag = "NGPlus@v4#4",
    NpcName = "大黄",
    NpcSprite = "执勤",
    Dialogue = "我的鼻子好用着呢。",
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus
-- Position: { 8900, 4320 }
DialogueConfig[107] = {
    Type = "Normal",
    DocTag = "NGPlus",
    NpcName = "大黄",
    NpcSprite = "",
    Dialogue = "",
    RotatePool = { 95, 96, 100, 103 },
    Next = -1  -- 下一段对话ID
}

-- 红顶入口（按序）：!Intro→2-A · !Summoned→2-hub · !Entered→2-C · !RoofWait→2-E · else→2-C
-- 普通对话类型  -- doc:entry#rr5
-- Position: { 4950, 150 }
DialogueConfig[108] = {
    Type = "Normal",
    DocTag = "entry#rr5",
    NpcName = "大黄",
    NpcSprite = "",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "RedRoof_RoofWaitShown", VarType = "bool", TrueNext = 92, FalseNext = -1 }
    },
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:entry#rr4
-- Position: { 4600, 150 }
DialogueConfig[109] = {
    Type = "Normal",
    DocTag = "entry#rr4",
    NpcName = "大黄",
    NpcSprite = "",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "RedRoof_RoofWaitShown", VarType = "bool", TrueNext = 108, FalseNext = 93 }
    },
    Next = 108  -- 下一段对话ID
}

-- 普通对话类型  -- doc:entry#rr3
-- Position: { 3900, 150 }
DialogueConfig[110] = {
    Type = "Normal",
    DocTag = "entry#rr3",
    NpcName = "大黄",
    NpcSprite = "",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "BlackCat_Entered", VarType = "bool", TrueNext = 109, FalseNext = 92 }
    },
    Next = 109  -- 下一段对话ID
}

-- 普通对话类型  -- doc:entry#rr2
-- Position: { 2150, 150 }
DialogueConfig[111] = {
    Type = "Normal",
    DocTag = "entry#rr2",
    NpcName = "大黄",
    NpcSprite = "",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "Dog_BlackCatSummoned", VarType = "bool", TrueNext = 110, FalseNext = 62 }
    },
    Next = 110  -- 下一段对话ID
}

-- 废弃旧门链节点（保留 ID 以免外部引用断裂；不再接入入口）
DialogueConfig[112] = {
    Type = "Normal",
    DocTag = "entry#rr2b-unused",
    NpcName = "大黄",
    NpcSprite = "",
    Dialogue = "",
    Next = -1
}

DialogueConfig[113] = {
    Type = "Normal",
    DocTag = "entry#rr2a-unused",
    NpcName = "大黄",
    NpcSprite = "",
    Dialogue = "",
    Next = -1
}

DialogueConfig[114] = {
    Type = "Normal",
    DocTag = "entry#rr2e-unused",
    NpcName = "大黄",
    NpcSprite = "",
    Dialogue = "",
    Next = -1
}

DialogueConfig[115] = {
    Type = "Normal",
    DocTag = "entry#rr2d-unused",
    NpcName = "大黄",
    NpcSprite = "",
    Dialogue = "",
    Next = -1
}

DialogueConfig[116] = {
    Type = "Normal",
    DocTag = "entry#rr2c-unused",
    NpcName = "大黄",
    NpcSprite = "",
    Dialogue = "",
    Next = -1
}

-- 普通对话类型  -- doc:entry#rr1
-- Position: { 1800, 150 }
DialogueConfig[117] = {
    Type = "Normal",
    DocTag = "entry#rr1",
    NpcName = "大黄",
    NpcSprite = "",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "RedRoof_IntroShown", VarType = "bool", TrueNext = 111, FalseNext = 58 }
    },
    Next = 111  -- 下一段对话ID
}

-- 普通对话类型  -- doc:entry#ds4
-- Position: { 1450, 150 }
DialogueConfig[118] = {
    Type = "Normal",
    DocTag = "entry#ds4",
    NpcName = "大黄",
    NpcSprite = "",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "DogStatus", VarType = "int", Op = "==", Value = 4, Next = 117 }
    },
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:entry#barn3
-- Position: { 1100, 150 }
DialogueConfig[119] = {
    Type = "Normal",
    DocTag = "entry#barn3",
    NpcName = "大黄",
    NpcSprite = "",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "DogStatus", VarType = "int", Op = "==", Value = 3, Next = 29 }
    },
    Next = 118  -- 下一段对话ID
}

-- 普通对话类型  -- doc:entry#barn2
-- Position: { 750, 150 }
DialogueConfig[120] = {
    Type = "Normal",
    DocTag = "entry#barn2",
    NpcName = "大黄",
    NpcSprite = "",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "DogStatus", VarType = "int", Op = "==", Value = 2, Next = 14 }
    },
    Next = 119  -- 下一段对话ID
}

-- 普通对话类型  -- doc:entry#barn1
-- Position: { 400, 150 }
DialogueConfig[121] = {
    Type = "Normal",
    DocTag = "entry#barn1",
    NpcName = "大黄",
    NpcSprite = "",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "DogStatus", VarType = "int", Op = "==", Value = 1, Next = 1 }
    },
    Next = 120  -- 下一段对话ID
}

-- doc:2-D skipped (cross-script trigger via 黑猫 2-E)
