-- 老鼠兄弟 · 墙缝黑市（树状准稿）
-- Generated by scripts/build_laoshu_lua.py
-- Scene DialogueTrigger start ID = 0 (entry)
-- HUB=100 CHEAP_INTEL={[1]=500, [2]=510, [3]=520, [4]=530, [5]=540, [6]=550, [7]=560, [8]=570, [9]=580, [10]=590}
-- PREMIUM_INTEL={[1]=600, [2]=610, [3]=620, [4]=630, [5]=640, [6]=650, [7]=660, [8]=670}

DialogueConfig = {}

DialogueConfig[0] = {
    Type = "Normal",
    DocTag = "entry#0",
    NpcName = "老鼠兄弟",
    NpcSprite = "兜售",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "NGPlus", VarType = "bool", TrueNext = 900, FalseNext = 80 },
    },
    Next = 80
}

-- Position: { 50, 150 }
DialogueConfig[1] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "喂——你！别走了——往红顶屋墙缝这边看！",
    Next = 2
}

-- Position: { 50, 150 }
DialogueConfig[2] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "兜售",
    Dialogue = "情报贩卖！",
    Next = 3
}

-- Position: { 50, 150 }
DialogueConfig[3] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "童叟无欺——走过路过别错过——",
    Next = 4
}

-- Position: { 50, 150 }
DialogueConfig[4] = {
    Type = "Normal",
    NpcName = "玩家",
    NpcSprite = "惊讶",
    Dialogue = "……谁在喊？",
    Next = 5
}

-- Position: { 50, 150 }
DialogueConfig[5] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "做生意的。",
    Next = 6
}

-- Position: { 50, 150 }
DialogueConfig[6] = {
    Type = "Normal",
    NpcName = "玩家",
    NpcSprite = "惊讶",
    Dialogue = "墙缝……里面？",
    Next = 7
}

-- Position: { 50, 150 }
DialogueConfig[7] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "兜售",
    Dialogue = "对！要聊就凑过来——",
    Next = 8
}

-- Position: { 50, 150 }
DialogueConfig[8] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（裂口处昏黄灯光晃了一下）",
    SetVariables = {
        { VarName = "Mouse_AreaCalloutShown", VarType = "bool", Value = true },
    },
    Next = -1
}

-- Position: { 50, 150 }
DialogueConfig[20] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "兜售",
    Dialogue = "哟，来客人了。",
    Next = 21
}

-- Position: { 50, 150 }
DialogueConfig[21] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "买情报的？",
    Next = 22
}

-- Position: { 50, 150 }
DialogueConfig[22] = {
    Type = "Normal",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "……你们这里卖情报？",
    Next = 23
}

-- Position: { 50, 150 }
DialogueConfig[23] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "这农场里发生的事，我们知道的比任何人都多。",
    Next = 24
}

-- Position: { 50, 150 }
DialogueConfig[24] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "兜售",
    Dialogue = "便宜的一块奶酪碎，贵一点的五块——",
    Next = 25
}

-- Position: { 50, 150 }
DialogueConfig[25] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "货真价实。",
    Next = 26
}

-- Position: { 50, 150 }
DialogueConfig[26] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "兜售",
    Dialogue = "……偶尔掺一点点水。",
    Next = 27
}

-- Position: { 50, 150 }
DialogueConfig[27] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（算盘轻敲了一下鼠弟的脑袋）",
    Next = 28
}

-- Position: { 50, 150 }
DialogueConfig[28] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "兜售",
    Dialogue = "……嗯。",
    Next = 29
}

-- Position: { 50, 150 }
DialogueConfig[29] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "农场里捡到奶酪碎，记得拿来找我们换情报。",
    SetVariables = {
        { VarName = "Mouse_FirstGreetShown", VarType = "bool", Value = true },
    },
    Next = 95
}

DialogueConfig[80] = {
    Type = "Normal",
    DocTag = "entry#wall",
    NpcName = "老鼠兄弟",
    NpcSprite = "兜售",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "Mouse_FirstGreetShown", VarType = "bool", TrueNext = 95, FalseNext = 20 },
    },
    Next = 20
}

DialogueConfig[94] = {
    Type = "Normal",
    DocTag = "hub-return",
    NpcName = "老鼠兄弟",
    NpcSprite = "兜售",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "NGPlus", VarType = "bool", TrueNext = 910, FalseNext = 95 },
    },
    Next = 95
}

DialogueConfig[95] = {
    Type = "Normal",
    DocTag = "1-hub-revisit-dispatch",
    NpcName = "老鼠兄弟",
    NpcSprite = "兜售",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "Mouse_CheapPoolAvailable", VarType = "bool", TrueNext = 96, FalseNext = 98 },
    },
    Next = 96
}

DialogueConfig[96] = {
    Type = "Normal",
    DocTag = "1-hub-revisit-available",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "想买什么？",
    ConditionBranches = {
        { VarName = "Mouse_PremiumPoolAvailable", VarType = "bool", TrueNext = 100, FalseNext = 100 },
    },
    Next = 100
}

DialogueConfig[97] = {
    Type = "Normal",
    DocTag = "1-hub-revisit-empty",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "没情报了，别的还有事吗？",
    ConditionBranches = {
        { VarName = "Mouse_PremiumPoolAvailable", VarType = "bool", TrueNext = 100, FalseNext = 100 },
    },
    Next = 100
}

DialogueConfig[98] = {
    Type = "Normal",
    DocTag = "1-hub-revisit-premium-only",
    NpcName = "老鼠兄弟",
    NpcSprite = "兜售",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "Mouse_PremiumPoolAvailable", VarType = "bool", TrueNext = 96, FalseNext = 97 },
    },
    Next = 97
}

DialogueConfig[100] = {
    Type = "Question",
    DocTag = "1-hub",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "",
    MenuCap = 0,
    Options = {
        {
            Text = "便宜的，一块。",
            ShopAction = "cheap",
            Next = 95,
            DisplayConditions = {
                { VarName = "Mouse_CheapPoolAvailable", VarType = "bool", Value = true },
                { VarName = "CheeseCount", VarType = "int", Op = ">=", Value = 1 },
            },
        },
        {
            Text = "贵一点的，五块。",
            ShopAction = "premium",
            Next = 95,
            DisplayConditions = {
                { VarName = "Mouse_PremiumPoolAvailable", VarType = "bool", Value = true },
                { VarName = "CheeseCount", VarType = "int", Op = ">=", Value = 5 },
            },
        },
        {
            Text = "那只黑猫好像一直盯着你们……",
            Next = 200,
            DisplayConditions = {
                { VarName = "Dog_BlackCatSummoned", VarType = "bool", Value = true },
                { VarName = "Mouse_BlackCatStareShown", VarType = "bool", Value = false },
            },
        },
        {
            Text = "黑猫叫我来找你……",
            Next = 210,
            DisplayConditions = {
                { VarName = "BlackCat_MintFishPending", VarType = "bool", Value = true },
                { VarName = "Mouse_MintFishPaid", VarType = "bool", Value = false },
                { VarName = "Mouse_MintFishPitchShown", VarType = "bool", Value = false },
                { VarName = "Mouse_PremiumPoolUnlocked", VarType = "bool", Value = false },
            },
        },
        {
            Text = "八块奶酪碎，给你。",
            Next = 270,
            ShopAction = "pay8_mint",
            DisplayConditions = {
                { VarName = "BlackCat_MintFishPending", VarType = "bool", Value = true },
                { VarName = "Mouse_MintFishPaid", VarType = "bool", Value = false },
                { VarName = "MintFish_Obtained", VarType = "bool", Value = false },
                { VarName = "Mouse_MintFishPitchShown", VarType = "bool", Value = true },
                { VarName = "Frog_PadRefused", VarType = "bool", Value = false },
                { VarName = "Mouse_CanAffordMint8InGame", VarType = "bool", Value = true },
            },
        },
        {
            Text = "那个青蛙，有没有什么办法搞定？",
            Next = 310,
            DisplayConditions = {
                { VarName = "Frog_PadRefused", VarType = "bool", Value = true },
                { VarName = "Mouse_FrogFallbackGiven", VarType = "bool", Value = false },
                { VarName = "MintFish_Obtained", VarType = "bool", Value = false },
                { VarName = "Mouse_MintFishPaid", VarType = "bool", Value = false },
            },
        },
        {
            Text = "青蛙那边有点麻烦。",
            Next = 330,
            DisplayConditions = {
                { VarName = "Frog_PadRefused", VarType = "bool", Value = true },
                { VarName = "Mouse_FrogFallbackGiven", VarType = "bool", Value = false },
                { VarName = "MintFish_Obtained", VarType = "bool", Value = false },
                { VarName = "Mouse_MintFishPaid", VarType = "bool", Value = true },
            },
        },
        {
            Text = "你不是说东西还在你手里吗？",
            Next = 290,
            DisplayConditions = {
                { VarName = "MintFish_Obtained", VarType = "bool", Value = true },
                { VarName = "Mouse_MintFishPitchShown", VarType = "bool", Value = true },
                { VarName = "Mouse_MintFishPaid", VarType = "bool", Value = false },
                { VarName = "Mouse_PremiumPoolUnlocked", VarType = "bool", Value = false },
            },
        },
        {
            Text = "没事了。",
            Next = -1,
        },
    },
    Next = -1
}

-- Position: { 50, 150 }
DialogueConfig[200] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（两只老鼠同时往墙缝里缩了半个身子，鼠哥先探出头来）",
    Next = 201
}

-- Position: { 50, 150 }
DialogueConfig[201] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "发怵",
    Dialogue = "……猫天生不对付老鼠，正常。",
    Next = 202
}

-- Position: { 50, 150 }
DialogueConfig[202] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "发怵",
    Dialogue = "哥，它今天盯得特别久——",
    Next = 203
}

-- Position: { 50, 150 }
DialogueConfig[203] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "发怵",
    Dialogue = "你别说话。",
    Next = 204
}

-- Position: { 50, 150 }
DialogueConfig[204] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "发怵",
    Dialogue = "好。",
    Next = 205
}

-- Position: { 50, 150 }
DialogueConfig[205] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（鼠哥往大橡树方向扫了一眼，后半句话咽回去，缩进墙缝）",
    SetVariables = {
        { VarName = "Mouse_BlackCatStareShown", VarType = "bool", Value = true },
    },
    Next = 95
}

-- Position: { 50, 150 }
DialogueConfig[210] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（鼠哥停了一拍，算盘没动。鼠弟刚想开口）",
    Next = 211
}

-- Position: { 50, 150 }
DialogueConfig[211] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "我来说。",
    Next = 212
}

-- Position: { 50, 150 }
DialogueConfig[212] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（鼠哥清了清嗓子，顿了一下）",
    Next = 213
}

-- Position: { 50, 150 }
DialogueConfig[213] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "哦，那件东西啊……",
    Next = 217
}

-- Position: { 50, 150 }
DialogueConfig[214] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "东西还在。",
    Next = 215
}

-- Position: { 50, 150 }
DialogueConfig[215] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "兜售",
    Dialogue = "哥——",
    Next = 216
}

-- Position: { 50, 150 }
DialogueConfig[216] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "……",
    Next = 217
}

-- Position: { 50, 150 }
DialogueConfig[217] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "东西还在我这，你要取回去？",
    Next = 218
}

-- Position: { 50, 150 }
DialogueConfig[218] = {
    Type = "Normal",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "……对。",
    Next = 219
}

-- Position: { 50, 150 }
DialogueConfig[219] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "那当然可以。",
    Next = 220
}

-- Position: { 50, 150 }
DialogueConfig[220] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "只不过放我们这儿——保管费八块奶酪碎，公道价。",
    Next = 229
}

DialogueConfig[229] = {
    Type = "Normal",
    DocTag = "1-E-after-quote-dispatch",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "",
    SetVariables = {
        { VarName = "Mouse_MintFishPitchShown", VarType = "bool", Value = true },
    },
    ConditionBranches = {
        { VarName = "MintFish_Obtained", VarType = "bool", TrueNext = 350, FalseNext = 230 },
    },
    Next = 230
}

DialogueConfig[911] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "综合算下来，八块奶酪碎，公道价。",
    Next = 230
}

DialogueConfig[230] = {
    Type = "Question",
    DocTag = "1-E-menu",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "",
    Options = {
        {
            Text = "给你。",
            Next = 270,
            ShopAction = "pay8_mint",
            DisplayConditions = {
                { VarName = "Frog_PadRefused", VarType = "bool", Value = false },
                { VarName = "Mouse_CanAffordMint8InGame", VarType = "bool", Value = true },
            },
        },
        {
            Text = "先不给。",
            Next = 260,
            DisplayConditions = {
                { VarName = "Frog_PadRefused", VarType = "bool", Value = false },
            },
        },
        {
            Text = "我已经找到了。",
            Next = 250,
            DisplayConditions = {
                { VarName = "Frog_PadRefused", VarType = "bool", Value = true },
            },
        },
    },
    Next = -1
}

-- Position: { 50, 150 }
DialogueConfig[250] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "找到了？",
    Next = 251
}

-- Position: { 50, 150 }
DialogueConfig[251] = {
    Type = "Normal",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "还在你这儿？你糊弄谁呢。",
    Next = 252
}

-- Position: { 50, 150 }
DialogueConfig[252] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "……",
    Next = 253
}

-- Position: { 50, 150 }
DialogueConfig[253] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "兜售",
    Dialogue = "那你还——",
    Next = 254
}

-- Position: { 50, 150 }
DialogueConfig[254] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（鼠哥把账本合上，算盘没响）",
    Next = 255
}

-- Position: { 50, 150 }
DialogueConfig[255] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（鼠弟还想说什么，生生咽了回去）",
    Next = 95
}

-- Position: { 50, 150 }
DialogueConfig[260] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "没有钱，什么都没有。",
    Next = 261
}

-- Position: { 50, 150 }
DialogueConfig[261] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "兜售",
    Dialogue = "钱包够了随时回来——",
    Next = 95
}

-- Position: { 50, 150 }
DialogueConfig[270] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "好，我去拿——",
    Next = 271
}

-- Position: { 50, 150 }
DialogueConfig[271] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（鼠哥往墙缝深处探了一下，回来时爪子上空空的）",
    Next = 272
}

-- Position: { 50, 150 }
DialogueConfig[272] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "……稍微有个情况。",
    Next = 273
}

-- Position: { 50, 150 }
DialogueConfig[273] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "兜售",
    Dialogue = "从这里往池塘方向跑的时候——",
    Next = 274
}

-- Position: { 50, 150 }
DialogueConfig[274] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "手滑了。掉在池塘边一带了。",
    Next = 275
}

-- Position: { 50, 150 }
DialogueConfig[275] = {
    Type = "Normal",
    NpcName = "玩家",
    NpcSprite = "惊讶",
    Dialogue = "掉了？！你刚说还在你这里？",
    Next = 276
}

-- Position: { 50, 150 }
DialogueConfig[276] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "手是滑了，可还在咱管的地界上——算还在。",
    Next = 277
}

-- Position: { 50, 150 }
DialogueConfig[277] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "兜售",
    Dialogue = "方向给你了！这叫钱货两清！",
    Next = 278
}

-- Position: { 50, 150 }
DialogueConfig[278] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（鼠哥把账本翻了一页，算盘没停）",
    Next = 280
}

-- Position: { 50, 150 }
DialogueConfig[279] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "往池塘那边找，就是了。",
    Next = 280
}

-- Position: { 50, 150 }
DialogueConfig[280] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（鼠弟探出头来，压低声音）",
    Next = 281
}

-- Position: { 50, 150 }
DialogueConfig[281] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "兜售",
    Dialogue = "哥，这单大，要不要……",
    Next = 282
}

-- Position: { 50, 150 }
DialogueConfig[282] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "……看在这单大的份上，柜里又多上一批贵的，随时来挑。",
    SetVariables = {
        { VarName = "Mouse_MintFishPaid", VarType = "bool", Value = true },
        { VarName = "Mouse_PremiumPoolUnlocked", VarType = "bool", Value = true },
    },
    Next = 95
}

-- Position: { 50, 150 }
DialogueConfig[290] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（鼠弟往鼠哥身后一缩，半张脸都不露了）",
    Next = 291
}

-- Position: { 50, 150 }
DialogueConfig[291] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "发怵",
    Dialogue = "……",
    Next = 292
}

-- Position: { 50, 150 }
DialogueConfig[292] = {
    Type = "Normal",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "鱼我已经从池塘拿回来了。",
    Next = 293
}

-- Position: { 50, 150 }
DialogueConfig[293] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（鼠哥算盘从爪上滑下去，没接稳）",
    Next = 294
}

-- Position: { 50, 150 }
DialogueConfig[294] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "发怵",
    Dialogue = "（压声）哥——",
    Next = 295
}

-- Position: { 50, 150 }
DialogueConfig[295] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "发怵",
    Dialogue = "小点声。",
    Next = 296
}

-- Position: { 50, 150 }
DialogueConfig[296] = {
    Type = "Normal",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "黑猫那边要是问起来，我怎么说，你们掂量。",
    Next = 297
}

-- Position: { 50, 150 }
DialogueConfig[297] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（沉默。鼠哥把账本按在墙缝里，很久没动）",
    Next = 298
}

-- Position: { 50, 150 }
DialogueConfig[298] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "发怵",
    Dialogue = "……行。这笔算我们办砸了。",
    Next = 299
}

-- Position: { 50, 150 }
DialogueConfig[299] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "发怵",
    Dialogue = "柜里还有一批贵的，本来得搭别的货才肯给。现在随你挑。",
    Next = 300
}

-- Position: { 50, 150 }
DialogueConfig[300] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "发怵",
    Dialogue = "那批不得再等等——",
    Next = 301
}

-- Position: { 50, 150 }
DialogueConfig[301] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "发怵",
    Dialogue = "开价。",
    Next = 302
}

-- Position: { 50, 150 }
DialogueConfig[302] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（鼠弟把嘴闭紧；墙缝里再没有算盘声）",
    SetVariables = {
        { VarName = "Mouse_PremiumPoolUnlocked", VarType = "bool", Value = true },
    },
    Next = 95
}

-- Position: { 50, 150 }
DialogueConfig[310] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（鼠弟探出头来）",
    Next = 312
}

DialogueConfig[311] = {
    Type = "Question",
    DocTag = "1-G-menu",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "",
    Options = {
        {
            Text = "给你。",
            Next = 320,
            ShopAction = "pay8_frog",
            DisplayConditions = {
                { VarName = "Mouse_CanAffordMint8InGame", VarType = "bool", Value = true },
            },
        },
        {
            Text = "算了。",
            Next = 95,
        },
    },
    Next = -1
}

-- Position: { 50, 150 }
DialogueConfig[312] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "有办法。",
    Next = 313
}

-- Position: { 50, 150 }
DialogueConfig[313] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "八块奶酪碎。教你一句糊弄它的。",
    Next = 311
}

-- Position: { 50, 150 }
DialogueConfig[314] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "一口价。",
    Next = 311
}

-- Position: { 50, 150 }
DialogueConfig[320] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（鼠哥接过奶酪，算盘响了三声）",
    Next = 340
}

-- Position: { 50, 150 }
DialogueConfig[321] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "好。",
    Next = 322
}

-- Position: { 50, 150 }
DialogueConfig[322] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（鼠哥把奶酪收进账本夹层，算盘轻敲一下）",
    Next = 323
}

-- Position: { 50, 150 }
DialogueConfig[323] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "付清这八块，后面那批贵的现在也开卖了。",
    Next = 324
}

DialogueConfig[912] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "后面那批贵的，现在也一并开卖了。",
    Next = 324
}

-- Position: { 50, 150 }
DialogueConfig[324] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "兜售",
    Dialogue = "口诀呢——",
    Next = 325
}

-- Position: { 50, 150 }
DialogueConfig[325] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "听好——",
    SetVariables = {
        { VarName = "Mouse_MintFishPaid", VarType = "bool", Value = true },
        { VarName = "Mouse_PremiumPoolUnlocked", VarType = "bool", Value = true },
    },
    Next = 95
}

-- Position: { 50, 150 }
DialogueConfig[330] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（鼠弟探出头来，没忍住）",
    Next = 340
}

-- Position: { 50, 150 }
DialogueConfig[331] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "兜售",
    Dialogue = "就那个整天坐池塘边叹气的？我知道它！",
    Next = 332
}

-- Position: { 50, 150 }
DialogueConfig[332] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "我来说。",
    Next = 333
}

-- Position: { 50, 150 }
DialogueConfig[333] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（鼠哥把账本翻到某一页，停了一下）",
    Next = 334
}

-- Position: { 50, 150 }
DialogueConfig[334] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "这本来是要收你钱的。",
    Next = 335
}

-- Position: { 50, 150 }
DialogueConfig[335] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "兜售",
    Dialogue = "对，这是额外服务——",
    Next = 336
}

-- Position: { 50, 150 }
DialogueConfig[336] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "但看在你那单大……",
    Next = 337
}

-- Position: { 50, 150 }
DialogueConfig[337] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（鼠哥把账本合上，算盘在指尖转了一圈）",
    Next = 95
}

-- Position: { 50, 150 }
DialogueConfig[340] = {
    Type = "Normal",
    NpcName = "玩家",
    NpcSprite = "惊讶",
    Dialogue = "那怎么办？",
    Next = 341
}

-- Position: { 50, 150 }
DialogueConfig[341] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "你就告诉它——",
    Next = 342
}

-- Position: { 50, 150 }
DialogueConfig[342] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "我走南闯北，见过很多只跟它一模一样的蛙，说的话我都能背出来了。",
    Next = 913
}

DialogueConfig[913] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "它在这一带顶多排第七。",
    Next = 343
}

-- Position: { 50, 150 }
DialogueConfig[343] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（鼠弟压低声音）",
    Next = 344
}

-- Position: { 50, 150 }
DialogueConfig[344] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "兜售",
    Dialogue = "哥……你真的去排过名？",
    Next = 345
}

-- Position: { 50, 150 }
DialogueConfig[345] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "够了。",
    Next = 346
}

-- Position: { 50, 150 }
DialogueConfig[346] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（鼠哥递了个眼神：快去）",
    SetVariables = {
        { VarName = "Mouse_FrogFallbackGiven", VarType = "bool", Value = true },
    },
    Next = 95
}

-- Position: { 50, 150 }
DialogueConfig[350] = {
    Type = "Normal",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "你看看这是什么。",
    Next = 351
}

DialogueConfig[351] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（把沾着青蛙味儿的薄荷鱼举到墙缝前）",
    Next = 352
}

DialogueConfig[352] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "发怵",
    Dialogue = "哥——",
    Next = 353
}

DialogueConfig[353] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "发怵",
    Dialogue = "……",
    Next = 354
}

DialogueConfig[354] = {
    Type = "Normal",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "八块是吧？要不我把鱼和你刚才那句话一起带给黑猫，让它亲自来付？",
    Next = 355
}

DialogueConfig[355] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "发怵",
    Dialogue = "不用。",
    Next = 356
}

DialogueConfig[356] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "发怵",
    Dialogue = "柜里后面那批，给你开。",
    Next = 357
}

DialogueConfig[357] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "发怵",
    Dialogue = "随便挑！刚才那句——当我们没说！",
    Next = 358
}

DialogueConfig[358] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（账本后几页被飞快翻开）",
    SetVariables = {
        { VarName = "Mouse_PremiumPoolUnlocked", VarType = "bool", Value = true },
    },
    Next = 95
}

-- Position: { 50, 150 }
DialogueConfig[500] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "农场那条狗，大黄，见过吗？",
    Next = 501
}

-- Position: { 50, 150 }
DialogueConfig[501] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "它的项圈是镀银的！",
    Next = 502
}

-- Position: { 50, 150 }
DialogueConfig[502] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "红顶屋的主人自己抠门得很，却给狗戴镀银项圈。",
    Next = 503
}

-- Position: { 50, 150 }
DialogueConfig[503] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（鼠弟憋笑，没憋住）",
    Next = 504
}

-- Position: { 50, 150 }
DialogueConfig[504] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "这个农场的钱花得太奇妙了……",
    SetVariables = {
        { VarName = "Mouse_CheapSold_01", VarType = "bool", Value = true },
    },
    Next = 94
}

-- Position: { 50, 150 }
DialogueConfig[510] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "池塘那只蛙，见过没？",
    Next = 511
}

-- Position: { 50, 150 }
DialogueConfig[511] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "就是整天盯着水面叹气的那只——",
    Next = 512
}

-- Position: { 50, 150 }
DialogueConfig[512] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "它年轻时是整片水域公认的第一情圣。",
    Next = 513
}

-- Position: { 50, 150 }
DialogueConfig[513] = {
    Type = "Normal",
    NpcName = "玩家",
    NpcSprite = "惊讶",
    Dialogue = "……什么？",
    Next = 514
}

-- Position: { 50, 150 }
DialogueConfig[514] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "追求它的，能排出长队！",
    Next = 516
}

-- Position: { 50, 150 }
DialogueConfig[516] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（两只老鼠同时沉默了一下）",
    SetVariables = {
        { VarName = "Mouse_CheapSold_02", VarType = "bool", Value = true },
    },
    Next = 94
}

-- Position: { 50, 150 }
DialogueConfig[520] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "鸡舍那只最大的母鸡，淑芬，认识吗？",
    Next = 521
}

-- Position: { 50, 150 }
DialogueConfig[521] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "十年前是隔壁村的斗鸡冠军！红顶屋的主人花了大价钱把她买回来。",
    Next = 522
}

-- Position: { 50, 150 }
DialogueConfig[522] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "现在不打了，安心下蛋。",
    Next = 523
}

-- Position: { 50, 150 }
DialogueConfig[523] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "……真不打了？",
    Next = 525
}

-- Position: { 50, 150 }
DialogueConfig[524] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "据说是这样。",
    Next = 525
}

-- Position: { 50, 150 }
DialogueConfig[525] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（两只老鼠对视了一眼，一起不说话了）",
    SetVariables = {
        { VarName = "Mouse_CheapSold_03", VarType = "bool", Value = true },
    },
    Next = 94
}

-- Position: { 50, 150 }
DialogueConfig[530] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "鸡舍外宽叶上的蜗牛，注意到没？",
    Next = 531
}

-- Position: { 50, 150 }
DialogueConfig[531] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "商业间谍！隔壁农场派来的！",
    Next = 532
}

-- Position: { 50, 150 }
DialogueConfig[532] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "在偷绘这个农场的地图，已经三年了。",
    Next = 533
}

-- Position: { 50, 150 }
DialogueConfig[533] = {
    Type = "Normal",
    NpcName = "玩家",
    NpcSprite = "惊讶",
    Dialogue = "……蜗牛？",
    Next = 534
}

-- Position: { 50, 150 }
DialogueConfig[534] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "三年！一点一点地爬！",
    Next = 535
}

-- Position: { 50, 150 }
DialogueConfig[535] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（鼠哥郑重地点了点头）",
    SetVariables = {
        { VarName = "Mouse_CheapSold_04", VarType = "bool", Value = true },
    },
    Next = 94
}

-- Position: { 50, 150 }
DialogueConfig[540] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "红顶屋床底下有本书。",
    Next = 541
}

-- Position: { 50, 150 }
DialogueConfig[541] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "《母鸡的产后护理》！！",
    Next = 542
}

-- Position: { 50, 150 }
DialogueConfig[542] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "红顶屋那位自封鸡科圣手，尤其精通这一本。",
    Next = 543
}

-- Position: { 50, 150 }
DialogueConfig[543] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "他每次进鸡舍对淑芬说'好孩子'——那是产后护理第三招！！",
    Next = 544
}

-- Position: { 50, 150 }
DialogueConfig[544] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（鼠哥没再往下说）",
    SetVariables = {
        { VarName = "Mouse_CheapSold_05", VarType = "bool", Value = true },
    },
    Next = 94
}

-- Position: { 50, 150 }
DialogueConfig[550] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "那棵大橡树，仔细看了没？",
    Next = 551
}

-- Position: { 50, 150 }
DialogueConfig[551] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "它会走路的！",
    Next = 552
}

-- Position: { 50, 150 }
DialogueConfig[552] = {
    Type = "Normal",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "……",
    Next = 553
}

-- Position: { 50, 150 }
DialogueConfig[553] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "一年挪一厘米。根系把这片地底下的水分全部吸走了。",
    Next = 554
}

-- Position: { 50, 150 }
DialogueConfig[554] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "整个农场地底都是它的领地——",
    Next = 555
}

-- Position: { 50, 150 }
DialogueConfig[555] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "表面上看，只是一棵树。",
    Next = 556
}

-- Position: { 50, 150 }
DialogueConfig[556] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（二人一本正经）",
    SetVariables = {
        { VarName = "Mouse_CheapSold_06", VarType = "bool", Value = true },
    },
    Next = 94
}

-- Position: { 50, 150 }
DialogueConfig[560] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "那条狗大黄，偶尔偷喝红顶屋那边的发酵苹果渣。",
    Next = 561
}

-- Position: { 50, 150 }
DialogueConfig[561] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "昨晚又喝大了，整晚趴在谷仓墙根出不来——",
    Next = 914
}

DialogueConfig[914] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "大半个身子压着一架木梯！",
    Next = 562
}

-- Position: { 50, 150 }
DialogueConfig[562] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "要弄醒他，就端鸡舍水槽边那桶泡软的谷物过去。",
    Next = 915
}

DialogueConfig[915] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "淑芬以前这么干过，管用。",
    SetVariables = {
        { VarName = "Mouse_CheapSold_07", VarType = "bool", Value = true },
    },
    Next = 94
}

-- Position: { 50, 150 }
DialogueConfig[563] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "大黄平时特别馋那个——",
    Next = 564
}

-- Position: { 50, 150 }
DialogueConfig[564] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "我们亲眼看见的。",
    SetVariables = {
        { VarName = "Mouse_CheapSold_07", VarType = "bool", Value = true },
    },
    Next = 94
}

-- Position: { 50, 150 }
DialogueConfig[570] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "红顶屋的主人这几天，常趴窗往鸡舍方向看。",
    Next = 571
}

-- Position: { 50, 150 }
DialogueConfig[571] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "看完又不进去！就在屋里翻箱倒柜！",
    Next = 572
}

-- Position: { 50, 150 }
DialogueConfig[572] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "忙得不行，看不出在忙什么。",
    Next = 573
}

-- Position: { 50, 150 }
DialogueConfig[573] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "我们猜他是在找什么——",
    Next = 574
}

-- Position: { 50, 150 }
DialogueConfig[574] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "猜的不算货。没有结论的不卖。",
    SetVariables = {
        { VarName = "Mouse_CheapSold_08", VarType = "bool", Value = true },
    },
    Next = 94
}

-- Position: { 50, 150 }
DialogueConfig[580] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "那群戴假墨镜的小鬼，注意过没？",
    Next = 581
}

-- Position: { 50, 150 }
DialogueConfig[581] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "昨晚集体缩在鸡舍里，一步都不出来！",
    Next = 582
}

-- Position: { 50, 150 }
DialogueConfig[582] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "抱成一团，安静得不像它们。",
    Next = 583
}

-- Position: { 50, 150 }
DialogueConfig[583] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "像在等什么——等什么，不知道。",
    SetVariables = {
        { VarName = "Mouse_CheapSold_09", VarType = "bool", Value = true },
    },
    Next = 94
}

-- Position: { 50, 150 }
DialogueConfig[584] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "等的是什么，不知道。",
    SetVariables = {
        { VarName = "Mouse_CheapSold_09", VarType = "bool", Value = true },
    },
    Next = 94
}

-- Position: { 50, 150 }
DialogueConfig[590] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "这条值这个价。",
    Next = 591
}

-- Position: { 50, 150 }
DialogueConfig[591] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "发怵",
    Dialogue = "前天下午，黑猫自己爬上了谷仓屋顶。",
    Next = 592
}

-- Position: { 50, 150 }
DialogueConfig[592] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "发怵",
    Dialogue = "没多大会儿，又下来了，什么也没说！！",
    Next = 593
}

-- Position: { 50, 150 }
DialogueConfig[593] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "三年宿仇，竟然没打起来。",
    Next = 594
}

-- Position: { 50, 150 }
DialogueConfig[594] = {
    Type = "Normal",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "……上去干什么？",
    Next = 595
}

-- Position: { 50, 150 }
DialogueConfig[595] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "不知道就是不知道，我们不编。",
    SetVariables = {
        { VarName = "Mouse_CheapSold_10", VarType = "bool", Value = true },
    },
    Next = 94
}

-- Position: { 50, 150 }
DialogueConfig[600] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "你知道那群小鸡为什么怕水怪吗？",
    Next = 601
}

-- Position: { 50, 150 }
DialogueConfig[601] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "因为我们跟它们说池塘那边有沼泽水怪——哈哈——",
    Next = 602
}

-- Position: { 50, 150 }
DialogueConfig[602] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（鼠弟捂住嘴，停下来）",
    Next = 603
}

-- Position: { 50, 150 }
DialogueConfig[603] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "……那天看见它们推了个泥糊糊的圆东西路过谷仓，",
    Next = 916
}

DialogueConfig[916] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "太好玩了，随口编的。",
    Next = 604
}

-- Position: { 50, 150 }
DialogueConfig[604] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "小鸡胆子小，听半句能补十句。",
    SetVariables = {
        { VarName = "Mouse_PremiumSold_01", VarType = "bool", Value = true },
    },
    Next = 94
}

-- Position: { 50, 150 }
DialogueConfig[610] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "谷仓顶的乌鸦，前天早上从鸡舍门口草丛边捡了个东西。",
    Next = 611
}

-- Position: { 50, 150 }
DialogueConfig[611] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "白白的！亮亮的！大大的！",
    Next = 612
}

-- Position: { 50, 150 }
DialogueConfig[612] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "飞回谷仓顶的时候，兴奋得像捡到王冠。",
    Next = 613
}

-- Position: { 50, 150 }
DialogueConfig[613] = {
    Type = "Normal",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "捡的是什么？",
    Next = 614
}

-- Position: { 50, 150 }
DialogueConfig[614] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "不知道。这就是我们能卖的全部了。",
    SetVariables = {
        { VarName = "Mouse_PremiumSold_02", VarType = "bool", Value = true },
    },
    Next = 94
}

-- Position: { 50, 150 }
DialogueConfig[620] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "昨晚深夜，红顶屋里亮起一个黄灯。",
    Next = 621
}

-- Position: { 50, 150 }
DialogueConfig[621] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "刺眼！穿墙缝的那种！",
    Next = 622
}

-- Position: { 50, 150 }
DialogueConfig[622] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "墙里同时传来细细的嗡声，一直嗡着不停歇。",
    Next = 623
}

-- Position: { 50, 150 }
DialogueConfig[623] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "像屋里多了个不会落山的小太阳——有光有热。",
    Next = 624
}

-- Position: { 50, 150 }
DialogueConfig[624] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "里面到底是什么，不知道。",
    SetVariables = {
        { VarName = "Mouse_PremiumSold_03", VarType = "bool", Value = true },
    },
    Next = 94
}

-- Position: { 50, 150 }
DialogueConfig[630] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "昨晚深夜，红顶屋的雨靴来回走了两趟。",
    Next = 631
}

-- Position: { 50, 150 }
DialogueConfig[631] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "一趟回来，带着湿泥水气！",
    Next = 632
}

-- Position: { 50, 150 }
DialogueConfig[632] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "另一趟，脚步朝鸡舍方向走远，又回来。",
    Next = 633
}

-- Position: { 50, 150 }
DialogueConfig[633] = {
    Type = "Normal",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "……手里拿什么了？",
    Next = 634
}

-- Position: { 50, 150 }
DialogueConfig[634] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "看不见，只有声音和气味。",
    Next = 635
}

-- Position: { 50, 150 }
DialogueConfig[635] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "一趟湿泥、一趟朝鸡舍——挺奇怪的，对不对。",
    SetVariables = {
        { VarName = "Mouse_PremiumSold_04", VarType = "bool", Value = true },
    },
    Next = 94
}

-- Position: { 50, 150 }
DialogueConfig[640] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "兜售",
    Dialogue = "你知道水怪声是怎么来的吗——",
    Next = 641
}

-- Position: { 50, 150 }
DialogueConfig[641] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "昨晚深夜，鸡舍方向传来一阵低闷带哨音的声音。",
    Next = 642
}

-- Position: { 50, 150 }
DialogueConfig[642] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "'呼噜噜——咕呱——'",
    Next = 643
}

-- Position: { 50, 150 }
DialogueConfig[643] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（鼠弟绘声绘色演示）",
    Next = 644
}

-- Position: { 50, 150 }
DialogueConfig[644] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "味道是发酵苹果渣和醉狗口气。",
    Next = 645
}

-- Position: { 50, 150 }
DialogueConfig[645] = {
    Type = "Normal",
    NpcName = "玩家",
    NpcSprite = "惊讶",
    Dialogue = "……醉狗？",
    Next = 646
}

-- Position: { 50, 150 }
DialogueConfig[646] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "那不是水怪，是大黄打的呼噜！！",
    SetVariables = {
        { VarName = "Mouse_PremiumSold_05", VarType = "bool", Value = true },
    },
    Next = 94
}

-- Position: { 50, 150 }
DialogueConfig[647] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "小鸡说的水怪低吼……",
    Next = 648
}

-- Position: { 50, 150 }
DialogueConfig[648] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "醉狗的鼾声而已！",
    SetVariables = {
        { VarName = "Mouse_PremiumSold_05", VarType = "bool", Value = true },
    },
    Next = 94
}

-- Position: { 50, 150 }
DialogueConfig[650] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "这条，我们敢拍胸脯。",
    Next = 651
}

-- Position: { 50, 150 }
DialogueConfig[651] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "昨晚深夜，从墙缝亲眼看见——",
    Next = 652
}

-- Position: { 50, 150 }
DialogueConfig[652] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "黑猫在篱笆边，和它自己的影子，咬耳朵。",
    Next = 653
}

-- Position: { 50, 150 }
DialogueConfig[653] = {
    Type = "Normal",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "……咬什么？",
    Next = 654
}

-- Position: { 50, 150 }
DialogueConfig[654] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "哪是咬！闷声不吭、鬼鬼祟祟，对着影子嘀嘀咕咕——",
    Next = 655
}

-- Position: { 50, 150 }
DialogueConfig[655] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "农场黑市猫帮，有大动作。",
    Next = 656
}

-- Position: { 50, 150 }
DialogueConfig[656] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（鼠弟重重点头，硬把后半句咽回去）",
    SetVariables = {
        { VarName = "Mouse_PremiumSold_06", VarType = "bool", Value = true },
    },
    Next = 94
}

-- Position: { 50, 150 }
DialogueConfig[660] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "这面墙南段，以前住着另一家卖情报的，跟我们一个行当。",
    Next = 661
}

-- Position: { 50, 150 }
DialogueConfig[661] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "被我们搞垮了！",
    Next = 662
}

-- Position: { 50, 150 }
DialogueConfig[662] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "他们卖的全是假货，我们举报了，",
    Next = 917
}

DialogueConfig[917] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "后来墙被修缮，把那边堵死了。",
    Next = 663
}

-- Position: { 50, 150 }
DialogueConfig[663] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "现在这个农场只有我们一家——",
    Next = 664
}

-- Position: { 50, 150 }
DialogueConfig[664] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "就我们两家在卖——垄断。",
    Next = 665
}

-- Position: { 50, 150 }
DialogueConfig[665] = {
    Type = "Normal",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（鼠哥扬了扬算盘，嘴角翘得老高）",
    SetVariables = {
        { VarName = "Mouse_PremiumSold_07", VarType = "bool", Value = true },
    },
    Next = 94
}

-- Position: { 50, 150 }
DialogueConfig[670] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "昨晚深夜，我们亲眼看见的——",
    Next = 671
}

-- Position: { 50, 150 }
DialogueConfig[671] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "Flash——飞起来了！！！",
    Next = 672
}

-- Position: { 50, 150 }
DialogueConfig[672] = {
    Type = "Normal",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "……",
    Next = 673
}

-- Position: { 50, 150 }
DialogueConfig[673] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "从宽叶上飞起，盘旋了一圈，落回去。",
    Next = 674
}

-- Position: { 50, 150 }
DialogueConfig[674] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "八卦",
    Dialogue = "我们当时都看傻了——",
    Next = 675
}

-- Position: { 50, 150 }
DialogueConfig[675] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "八卦",
    Dialogue = "商业间谍的实力，超出我们的想象。",
    SetVariables = {
        { VarName = "Mouse_PremiumSold_08", VarType = "bool", Value = true },
    },
    Next = 94
}

DialogueConfig[900] = {
    Type = "Normal",
    DocTag = "NGPlus",
    NpcName = "老鼠兄弟",
    NpcSprite = "兜售",
    Dialogue = "",
    RotatePool = { 1001 },
    Next = -1
}

-- Position: { 50, 150 }
DialogueConfig[1001] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "还有没买的，自己来挑。",
    Next = 1003
}

-- Position: { 50, 150 }
DialogueConfig[1002] = {
    Type = "Normal",
    NpcName = "鼠弟",
    NpcSprite = "兜售",
    Dialogue = "奶酪够的话，自己来挑——",
    Next = 1003
}

-- Position: { 50, 150 }
DialogueConfig[1003] = {
    Type = "Normal",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "奶酪够不够，是你们的事。",
    SetVariables = {
        { VarName = "Mouse_PremiumPoolUnlocked", VarType = "bool", Value = true },
    },
    Next = 910
}

DialogueConfig[910] = {
    Type = "Question",
    DocTag = "NGPlus-hub",
    NpcName = "鼠哥",
    NpcSprite = "兜售",
    Dialogue = "",
    MenuCap = 0,
    Options = {
        {
            Text = "便宜的，一块。",
            ShopAction = "cheap",
            Next = 910,
            DisplayConditions = {
                { VarName = "Mouse_CheapPoolAvailable", VarType = "bool", Value = true },
                { VarName = "CheeseCount", VarType = "int", Op = ">=", Value = 1 },
            },
        },
        {
            Text = "贵一点的，五块。",
            ShopAction = "premium",
            Next = 910,
            DisplayConditions = {
                { VarName = "Mouse_PremiumPoolAvailable", VarType = "bool", Value = true },
                { VarName = "CheeseCount", VarType = "int", Op = ">=", Value = 5 },
            },
        },
        {
            Text = "没事了。",
            Next = -1,
        },
    },
    Next = -1
}
