-- 对话配置文件
-- Generated by doc_to_lua.py (Phase 2 — do not overwrite production files)
-- Scene DialogueTrigger start ID should be 0 (entry dispatcher)
-- doc node map:
--   1-A -> DialogueConfig[1]
--   1-hub-intro -> DialogueConfig[23]
--   1-hub -> DialogueConfig[24]
--   1-B -> DialogueConfig[25]
--   1-C -> DialogueConfig[31]
--   1-D -> DialogueConfig[35]
--   1-E -> DialogueConfig[40]
--   1-F -> DialogueConfig[45]
--   1-G -> DialogueConfig[48]
--   2-A -> DialogueConfig[56]
--   3-A -> DialogueConfig[73]
--   NGPlus -> DialogueConfig[91]
--   NGPlus-revisit -> DialogueConfig[88]

--   __entry__ -> DialogueConfig[0]
--   __entry__ -> DialogueConfig[0]
--   entry#comm -> DialogueConfig[89]
--   entry#new -> DialogueConfig[90]
--   entry#ng1 -> DialogueConfig[103]
--   entry#ng2 -> DialogueConfig[104]
DialogueConfig = {}

-- 普通对话类型  -- doc:1-A#1
-- Position: { 50, 150 }
DialogueConfig[1] = {
    Type = "Normal",
    DocTag = "1-A#1",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（鸡舍门口，一只母鸡正站着，忽然抬起头来）",
    Next = 2  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-A#2
-- Position: { 400, 150 }
DialogueConfig[2] = {
    Type = "Normal",
    DocTag = "1-A#2",
    NpcName = "淑芬",
    NpcSprite = "守望",
    Dialogue = "哎——你等一下！",
    Next = 3  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-A#3
-- Position: { 750, 150 }
DialogueConfig[3] = {
    Type = "Normal",
    DocTag = "1-A#3",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "帮个忙行不行？我找不到孩儿了——",
    Next = 4  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-A#4
-- Position: { 1100, 150 }
DialogueConfig[4] = {
    Type = "Normal",
    DocTag = "1-A#4",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（往鸡窝方向领了一步，又回头张望）",
    Next = 5  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-A#5
-- Position: { 1450, 150 }
DialogueConfig[5] = {
    Type = "Normal",
    DocTag = "1-A#5",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "今早发现，我画了爱心标记的那最后一颗蛋，没了。",
    Next = 6  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-A#6
-- Position: { 1800, 150 }
DialogueConfig[6] = {
    Type = "Normal",
    DocTag = "1-A#6",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "其他孩子出壳都好几天了，就这最小的——",
    Next = 200
}

DialogueConfig[200] = {
    Type = "Normal",
    DocTag = "1-A#6b",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "迟迟没动静，我一直守着它。",
    Next = 7
}

-- 普通对话类型  -- doc:1-A#7
-- Position: { 2150, 150 }
DialogueConfig[7] = {
    Type = "Normal",
    DocTag = "1-A#7",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "昨晚之前还动过一下，那种感觉……我不可能认错的。",
    Next = 8  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-A#8
-- Position: { 2500, 150 }
DialogueConfig[8] = {
    Type = "Normal",
    DocTag = "1-A#8",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（停了停，看了看天）",
    Next = 9  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-A#9
-- Position: { 2850, 150 }
DialogueConfig[9] = {
    Type = "Normal",
    DocTag = "1-A#9",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "最近天骤然凉了，我就担心——",
    Next = 10  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-A#10
-- Position: { 3200, 150 }
DialogueConfig[10] = {
    Type = "Normal",
    DocTag = "1-A#10",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "主人也来看了好几回，就那样站着不说话。",
    Next = 11  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-A#11
-- Position: { 3550, 150 }
DialogueConfig[11] = {
    Type = "Normal",
    DocTag = "1-A#11",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "你帮我找找吧，行吗？",
    Next = 12  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-A#12
-- Position: { 3900, 150 }
DialogueConfig[12] = {
    Type = "Normal",
    DocTag = "1-A#12",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "交给我。我去找。",
    Next = 13  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-A#13
-- Position: { 4250, 150 }
DialogueConfig[13] = {
    Type = "Normal",
    DocTag = "1-A#13",
    NpcName = "淑芬",
    NpcSprite = "守望",
    Dialogue = "谢谢你，真的。有什么要问的，随时来找我——",
    Next = 201
}

DialogueConfig[201] = {
    Type = "Normal",
    DocTag = "1-A#13b",
    NpcName = "淑芬",
    NpcSprite = "守望",
    Dialogue = "农场的事我比谁都熟。我就在鸡舍这边。",
    SetVariables = {
        { VarName = "Shufen_CommissionDone", VarType = "bool", Value = true }
    },
    Next = -1
}

-- 普通对话类型  -- doc:1-hub-intro@v1#1
-- Position: { 3400, 1150 }
DialogueConfig[14] = {
    Type = "Normal",
    DocTag = "1-hub-intro@v1#1",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "你来了，快进来。",
    Next = 15  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-hub-intro@v1#2
-- Position: { 3750, 1150 }
DialogueConfig[15] = {
    Type = "Normal",
    DocTag = "1-hub-intro@v1#2",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "有发现吗？",
    Next = 16  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-hub-intro@v1#3
-- Position: { 4100, 1150 }
DialogueConfig[16] = {
    Type = "Normal",
    DocTag = "1-hub-intro@v1#3",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（身子往前倾了倾，又收住）",
    Next = 24  -- 下一段对话ID（1-hub）
}

-- 普通对话类型  -- doc:1-hub-intro@v2#1
-- Position: { 3400, 1430 }
DialogueConfig[17] = {
    Type = "Normal",
    DocTag = "1-hub-intro@v2#1",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（听见动静，猛地抬起头）",
    Next = 18  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-hub-intro@v2#2
-- Position: { 3750, 1430 }
DialogueConfig[18] = {
    Type = "Normal",
    DocTag = "1-hub-intro@v2#2",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "哦，是你！",
    Next = 19  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-hub-intro@v2#3
-- Position: { 4100, 1430 }
DialogueConfig[19] = {
    Type = "Normal",
    DocTag = "1-hub-intro@v2#3",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "……怎么样了，有消息了吗？",
    Next = 20  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-hub-intro@v2#4
-- Position: { 4450, 1250 }
DialogueConfig[20] = {
    Type = "Normal",
    DocTag = "1-hub-intro@v2#4",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（拢了拢翅膀，别过脸去）",
    Next = 24  -- 下一段对话ID（1-hub）
}

-- 普通对话类型  -- doc:1-hub-intro@v3#1
-- Position: { 3400, 1710 }
DialogueConfig[21] = {
    Type = "Normal",
    DocTag = "1-hub-intro@v3#1",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "来了啊，进来坐。",
    Next = 22  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-hub-intro@v3#2
-- Position: { 3750, 1710 }
DialogueConfig[22] = {
    Type = "Normal",
    DocTag = "1-hub-intro@v3#2",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（往窝边扫了一眼，目光停了停）",
    Next = 24  -- 下一段对话ID（1-hub）
}

-- 普通对话类型  -- doc:1-hub-intro
-- Position: { 3400, 1990 }
DialogueConfig[23] = {
    Type = "Normal",
    DocTag = "1-hub-intro",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "",
    RotatePool = { 14, 17, 21 },
    Next = 24  -- 下一段对话ID
}

-- 提问类型（玩家需要选择回答）  -- doc:1-hub
-- Position: { 2950, 1250 }
DialogueConfig[24] = {
    Type = "Question",
    DocTag = "1-hub",
    NpcName = "淑芬",
    NpcSprite = "守望",
    Dialogue = "……还有什么我能做的吗？",
    Options = {
        {
            Text = "发现和蛋有关的，你看……",
            Next = 56,
            DisplayConditions = {
                { VarName = "E10_ViewWhiteStone", VarType = "bool", Value = true },
                { VarName = "Shufen_StoneRevealShown", VarType = "bool", Value = false }
            },
        },
        {
            Text = "我觉得……主人把蛋带走了。",
            Next = 73,
            DisplayConditions = {
                { VarName = "DogStatus", VarType = "int", Op = "==", Value = 4 },
                { VarName = "Shufen_MasterTrustShown", VarType = "bool", Value = false }
            },
        },
        {
            Text = "主人最近老在你窝边转？",
            Next = 25,
            DisplayConditions = {
                { VarName = "Shufen_MasterAsked", VarType = "bool", Value = false }
            },
        },
        {
            Text = "大黄喝多了，怎么叫醒？",
            Next = 48,
            DisplayConditions = {
                { VarName = "DogStatus", VarType = "int", Op = ">=", Value = 2 },
                { VarName = "E05_GrainSoakGet", VarType = "bool", Value = false },
                { VarName = "Shufen_DaHuangWakeAsked", VarType = "bool", Value = false }
            },
        },
        {
            Text = "那只乌鸦，你觉得它知道什么吗？",
            Next = 31,
            DisplayConditions = {
                { VarName = "DogStatus", VarType = "int", Op = ">=", Value = 2 },
                { VarName = "Shufen_CrowAsked", VarType = "bool", Value = false },
                { VarName = "Crow_RoofIntroShown", VarType = "bool", Value = false }
            },
        },
        {
            Text = "池塘边那只青蛙，你了解它吗？",
            Next = 35,
            DisplayConditions = {
                { VarName = "Frog_FirstMeetShown", VarType = "bool", Value = true },
                { VarName = "Shufen_FrogAsked", VarType = "bool", Value = false }
            },
        },
        {
            Text = "红顶屋老鼠，你知道事吗？",
            Next = 40,
            DisplayConditions = {
                { VarName = "Mouse_FirstGreetShown", VarType = "bool", Value = true },
                { VarName = "Shufen_MouseAsked", VarType = "bool", Value = false }
            },
        },
        {
            Text = "谷仓午睡草窝——是你的吗？",
            Next = 45,
            DisplayConditions = {
                { VarName = "E07_ViewNapSpot", VarType = "bool", Value = true },
                { VarName = "Shufen_NapSpotAsked", VarType = "bool", Value = false }
            },
        },
        {
            Text = "我再去找找别的线索。",
            Next = -1,
        }
    }
}

-- 普通对话类型  -- doc:1-B#1
-- Position: { 4700, 150 }
DialogueConfig[25] = {
    Type = "Normal",
    DocTag = "1-B#1",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "主人那边……你说他最近老在你窝边转悠？",
    Next = 26  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-B#2
-- Position: { 5050, 150 }
DialogueConfig[26] = {
    Type = "Normal",
    DocTag = "1-B#2",
    NpcName = "淑芬",
    NpcSprite = "守望",
    Dialogue = "就是老来窝边——有时候弯腰往里看，有时候只是站着。",
    Next = 27  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-B#3
-- Position: { 5400, 150 }
DialogueConfig[27] = {
    Type = "Normal",
    DocTag = "1-B#3",
    NpcName = "淑芬",
    NpcSprite = "守望",
    Dialogue = "我赶他，他就往后退半步，过一会儿又靠过来。",
    Next = 28  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-B#4
-- Position: { 5750, 150 }
DialogueConfig[28] = {
    Type = "Normal",
    DocTag = "1-B#4",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（停顿了一下）",
    Next = 29  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-B#5
-- Position: { 6100, 150 }
DialogueConfig[29] = {
    Type = "Normal",
    DocTag = "1-B#5",
    NpcName = "淑芬",
    NpcSprite = "守望",
    Dialogue = "他就是这样，担心的事放不下，但又不会说。",
    Next = 30  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-B#6
-- Position: { 6450, 150 }
DialogueConfig[30] = {
    Type = "Normal",
    DocTag = "1-B#6",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "来了我就知道，他也在惦记着孩儿。",
    SetVariables = {
        { VarName = "Shufen_MasterAsked", VarType = "bool", Value = true }
    },
    Next = 24  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-C#1
-- Position: { 6900, 150 }
DialogueConfig[31] = {
    Type = "Normal",
    DocTag = "1-C#1",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "那只乌鸦，你觉得它知道什么吗？",
    Next = 32  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-C#2
-- Position: { 7250, 150 }
DialogueConfig[32] = {
    Type = "Normal",
    DocTag = "1-C#2",
    NpcName = "淑芬",
    NpcSprite = "守望",
    Dialogue = "那只乌鸦啊，什么东西都往顶上搬——",
    Next = 202
}

DialogueConfig[202] = {
    Type = "Normal",
    DocTag = "1-C#2b",
    NpcName = "淑芬",
    NpcSprite = "守望",
    Dialogue = "亮的、白的、圆的，见了就往顶上叼。",
    Next = 33
}

-- 普通对话类型  -- doc:1-C#3
-- Position: { 7600, 150 }
DialogueConfig[33] = {
    Type = "Normal",
    DocTag = "1-C#3",
    NpcName = "淑芬",
    NpcSprite = "守望",
    Dialogue = "谷仓顶堆了一堆，它自己稀罕得很，我们都懒得管它。",
    Next = 34  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-C#4
-- Position: { 7950, 150 }
DialogueConfig[34] = {
    Type = "Normal",
    DocTag = "1-C#4",
    NpcName = "淑芬",
    NpcSprite = "守望",
    Dialogue = "你要找丢了的东西，去它那翻翻也好。",
    SetVariables = {
        { VarName = "Shufen_CrowAsked", VarType = "bool", Value = true }
    },
    Next = 24  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-D#1
-- Position: { 50, 700 }
DialogueConfig[35] = {
    Type = "Normal",
    DocTag = "1-D#1",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "池塘边那只青蛙，你了解它吗？",
    Next = 36  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-D#2
-- Position: { 400, 700 }
DialogueConfig[36] = {
    Type = "Normal",
    DocTag = "1-D#2",
    NpcName = "淑芬",
    NpcSprite = "守望",
    Dialogue = "那只蛙啊……",
    Next = 37  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-D#3
-- Position: { 750, 700 }
DialogueConfig[37] = {
    Type = "Normal",
    DocTag = "1-D#3",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（轻轻摇了摇头）",
    Next = 38  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-D#4
-- Position: { 1100, 700 }
DialogueConfig[38] = {
    Type = "Normal",
    DocTag = "1-D#4",
    NpcName = "淑芬",
    NpcSprite = "守望",
    Dialogue = "说的东西听不太懂。可它就待在水边——",
    Next = 203
}

DialogueConfig[203] = {
    Type = "Normal",
    DocTag = "1-D#4b",
    NpcName = "淑芬",
    NpcSprite = "守望",
    Dialogue = "什么路过的都看在眼里。",
    Next = 39
}

-- 普通对话类型  -- doc:1-D#5
-- Position: { 1450, 700 }
DialogueConfig[39] = {
    Type = "Normal",
    DocTag = "1-D#5",
    NpcName = "淑芬",
    NpcSprite = "守望",
    Dialogue = "你去问问，就是耐心点——说话绕，多问几句。",
    SetVariables = {
        { VarName = "Shufen_FrogAsked", VarType = "bool", Value = true }
    },
    Next = 24  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-E#1
-- Position: { 1900, 700 }
DialogueConfig[40] = {
    Type = "Normal",
    DocTag = "1-E#1",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "红顶屋那俩老鼠，你知道它们的事吗？",
    Next = 41  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-E#2
-- Position: { 2250, 700 }
DialogueConfig[41] = {
    Type = "Normal",
    DocTag = "1-E#2",
    NpcName = "淑芬",
    NpcSprite = "守望",
    Dialogue = "你跑去找那两个了？",
    Next = 42  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-E#3
-- Position: { 2600, 700 }
DialogueConfig[42] = {
    Type = "Normal",
    DocTag = "1-E#3",
    NpcName = "淑芬",
    NpcSprite = "守望",
    Dialogue = "那俩……消息是有的，就是爱掺水。",
    Next = 43  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-E#4
-- Position: { 2950, 700 }
DialogueConfig[43] = {
    Type = "Normal",
    DocTag = "1-E#4",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（翅膀拢了拢）",
    Next = 44  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-E#5
-- Position: { 3300, 700 }
DialogueConfig[44] = {
    Type = "Normal",
    DocTag = "1-E#5",
    NpcName = "淑芬",
    NpcSprite = "守望",
    Dialogue = "你要问，我不拦——自己分辨一下，哪句是真的，哪句是瞎掰的。",
    SetVariables = {
        { VarName = "Shufen_MouseAsked", VarType = "bool", Value = true }
    },
    Next = 24  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-F#1
-- Position: { 3750, 700 }
DialogueConfig[45] = {
    Type = "Normal",
    DocTag = "1-F#1",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "谷仓那边有个草窝——那是你的午睡点吗？",
    Next = 46  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-F#2
-- Position: { 4100, 700 }
DialogueConfig[46] = {
    Type = "Normal",
    DocTag = "1-F#2",
    NpcName = "淑芬",
    NpcSprite = "守望",
    Dialogue = "不是我，我不跑那么远。",
    Next = 47  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-F#3
-- Position: { 4450, 700 }
DialogueConfig[47] = {
    Type = "Normal",
    DocTag = "1-F#3",
    NpcName = "淑芬",
    NpcSprite = "守望",
    Dialogue = "鸡舍这边就挺好的……",
    SetVariables = {
        { VarName = "Shufen_NapSpotAsked", VarType = "bool", Value = true }
    },
    Next = 24  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-G#1
-- Position: { 50, 1250 }
DialogueConfig[48] = {
    Type = "Normal",
    DocTag = "1-G#1",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "大黄好像喝多了，有什么办法把他叫醒吗？",
    Next = 49  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-G#2
-- Position: { 400, 1250 }
DialogueConfig[49] = {
    Type = "Normal",
    DocTag = "1-G#2",
    NpcName = "淑芬",
    NpcSprite = "守望",
    Dialogue = "那条蠢狗又喝多了？",
    Next = 50  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-G#3
-- Position: { 750, 1250 }
DialogueConfig[50] = {
    Type = "Normal",
    DocTag = "1-G#3",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（叹了口气）",
    Next = 51  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-G#4
-- Position: { 1100, 1250 }
DialogueConfig[51] = {
    Type = "Normal",
    DocTag = "1-G#4",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "狗窝都空着——准又醉在谷仓那边了。",
    Next = 52  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-G#5
-- Position: { 1450, 1250 }
DialogueConfig[52] = {
    Type = "Normal",
    DocTag = "1-G#5",
    NpcName = "淑芬",
    NpcSprite = "守望",
    Dialogue = "你直接喊是喊不醒的，喝成那样。",
    Next = 53  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-G#6
-- Position: { 1800, 1250 }
DialogueConfig[53] = {
    Type = "Normal",
    DocTag = "1-G#6",
    NpcName = "淑芬",
    NpcSprite = "守望",
    Dialogue = "鸡舍水槽边有桶老谷物泡的水，他爱喝那个味儿，",
    Next = 204
}

DialogueConfig[204] = {
    Type = "Normal",
    DocTag = "1-G#6b",
    NpcName = "淑芬",
    NpcSprite = "守望",
    Dialogue = "灌下去就醒了。",
    Next = 54
}

-- 普通对话类型  -- doc:1-G#7
-- Position: { 2150, 1250 }
DialogueConfig[54] = {
    Type = "Normal",
    DocTag = "1-G#7",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（停了一下）",
    Next = 55  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-G#8
-- Position: { 2500, 1250 }
DialogueConfig[55] = {
    Type = "Normal",
    DocTag = "1-G#8",
    NpcName = "淑芬",
    NpcSprite = "守望",
    Dialogue = "……上次也是我给他端去的。",
    SetVariables = {
        { VarName = "Shufen_DaHuangWakeAsked", VarType = "bool", Value = true }
    },
    Next = 24  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#1
-- Position: { 9250, 150 }
DialogueConfig[56] = {
    Type = "Normal",
    DocTag = "2-A#1",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "谷仓顶上有颗石头，上面画着爱心和鬼脸——你看，长这样。",
    Next = 57  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#2
-- Position: { 9600, 150 }
DialogueConfig[57] = {
    Type = "Normal",
    DocTag = "2-A#2",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（盯着笔记本，半天没动）",
    Next = 58  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#3
-- Position: { 9950, 150 }
DialogueConfig[58] = {
    Type = "Normal",
    DocTag = "2-A#3",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "……这是石头？",
    Next = 59  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#4
-- Position: { 10300, 150 }
DialogueConfig[59] = {
    Type = "Normal",
    DocTag = "2-A#4",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（低头再看了一眼，抬起头）",
    Next = 60  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#5
-- Position: { 10650, 150 }
DialogueConfig[60] = {
    Type = "Normal",
    DocTag = "2-A#5",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "石头。",
    Next = 61  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#6
-- Position: { 11000, 150 }
DialogueConfig[61] = {
    Type = "Normal",
    DocTag = "2-A#6",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "大前天下午，我离窝去转了一圈，搞了搞沙浴，",
    Next = 205
}

DialogueConfig[205] = {
    Type = "Normal",
    DocTag = "2-A#6b",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "就那一小会儿。",
    Next = 62
}

-- 普通对话类型  -- doc:2-A#7
-- Position: { 11350, 150 }
DialogueConfig[62] = {
    Type = "Normal",
    DocTag = "2-A#7",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "回来一摸，蛋是冰冰凉的。",
    Next = 63  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#8
-- Position: { 11700, 150 }
DialogueConfig[63] = {
    Type = "Normal",
    DocTag = "2-A#8",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（停了停；嗓门低了下去）",
    Next = 64  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#9
-- Position: { 12050, 150 }
DialogueConfig[64] = {
    Type = "Normal",
    DocTag = "2-A#9",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "心一下子空了。我满院子跑，深蹲做到腿软，",
    Next = 206
}

DialogueConfig[206] = {
    Type = "Normal",
    DocTag = "2-A#9b",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "想要把孩儿焐回来。",
    Next = 65
}

-- 普通对话类型  -- doc:2-A#10
-- Position: { 12400, 150 }
DialogueConfig[65] = {
    Type = "Normal",
    DocTag = "2-A#10",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "跑累了回窝，蛋居然又热了。",
    Next = 66  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#11
-- Position: { 12750, 150 }
DialogueConfig[66] = {
    Type = "Normal",
    DocTag = "2-A#11",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "我还以为是自己把孩儿焐热的。",
    Next = 67  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#12
-- Position: { 13100, 150 }
DialogueConfig[67] = {
    Type = "Normal",
    DocTag = "2-A#12",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（喙用力抿住）",
    Next = 68  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#13
-- Position: { 13450, 150 }
DialogueConfig[68] = {
    Type = "Normal",
    DocTag = "2-A#13",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "那几个小崽子！阿满！你带他们干什么好事了！？",
    Next = 69  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#14
-- Position: { 13800, 150 }
DialogueConfig[69] = {
    Type = "Normal",
    DocTag = "2-A#14",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "让我逮到，一个个都得打一顿！",
    Next = 70  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#15
-- Position: { 14150, 150 }
DialogueConfig[70] = {
    Type = "Normal",
    DocTag = "2-A#15",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（停了片刻；翅膀松了松）",
    Next = 71  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#16
-- Position: { 14500, 150 }
DialogueConfig[71] = {
    Type = "Normal",
    DocTag = "2-A#16",
    NpcName = "淑芬",
    NpcSprite = "守望",
    Dialogue = "……大前天下午是虚惊一场。",
    Next = 72  -- 下一段对话ID
}

-- 普通对话类型  -- doc:2-A#17
-- Position: { 14850, 150 }
DialogueConfig[72] = {
    Type = "Normal",
    DocTag = "2-A#17",
    NpcName = "淑芬",
    NpcSprite = "守望",
    Dialogue = "孩儿是今早才不见的。谢谢你找到这个。",
    SetVariables = {
        { VarName = "Shufen_StoneRevealShown", VarType = "bool", Value = true }
    },
    Next = 24  -- 下一段对话ID
}

-- 普通对话类型  -- doc:3-A#2
-- Position: { 50, 2540 }
DialogueConfig[73] = {
    Type = "Normal",
    DocTag = "3-A#2",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "我觉得……主人把蛋带走了。",
    Next = 74  -- 下一段对话ID
}

-- 普通对话类型  -- doc:3-A#3
-- Position: { 400, 2540 }
DialogueConfig[74] = {
    Type = "Normal",
    DocTag = "3-A#3",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（皱眉，想了想）",
    Next = 75  -- 下一段对话ID
}

-- 普通对话类型  -- doc:3-A#4
-- Position: { 750, 2540 }
DialogueConfig[75] = {
    Type = "Normal",
    DocTag = "3-A#4",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "……主人？",
    Next = 76  -- 下一段对话ID
}

-- 普通对话类型  -- doc:3-A#5
-- Position: { 1100, 2540 }
DialogueConfig[76] = {
    Type = "Normal",
    DocTag = "3-A#5",
    NpcName = "淑芬",
    NpcSprite = "守望",
    Dialogue = "主人绝对不是坏人。",
    Next = 77  -- 下一段对话ID
}

-- 普通对话类型  -- doc:3-A#6
-- Position: { 1450, 2540 }
DialogueConfig[77] = {
    Type = "Normal",
    DocTag = "3-A#6",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "大前天我急疯了满院子跑那会儿——他就站旁边看着，也很担心。",
    Next = 78  -- 下一段对话ID
}

-- 普通对话类型  -- doc:3-A#7
-- Position: { 1800, 2540 }
DialogueConfig[78] = {
    Type = "Normal",
    DocTag = "3-A#7",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（羽毛微微绷了一下）",
    Next = 79  -- 下一段对话ID
}

-- 普通对话类型  -- doc:3-A#8
-- Position: { 2150, 2540 }
DialogueConfig[79] = {
    Type = "Normal",
    DocTag = "3-A#8",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "不会有事的。",
    Next = 80  -- 下一段对话ID
}

-- 普通对话类型  -- doc:3-A#9
-- Position: { 2500, 2540 }
DialogueConfig[80] = {
    Type = "Normal",
    DocTag = "3-A#9",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（声音压得很轻）",
    Next = 81  -- 下一段对话ID
}

-- 普通对话类型  -- doc:3-A#10
-- Position: { 2850, 2540 }
DialogueConfig[81] = {
    Type = "Normal",
    DocTag = "3-A#10",
    NpcName = "淑芬",
    NpcSprite = "守望",
    Dialogue = "……不会有事的。",
    SetVariables = {
        { VarName = "Shufen_MasterTrustShown", VarType = "bool", Value = true }
    },
    Next = 24  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus-revisit@v1#1
-- Position: { 9250, 1450 }
DialogueConfig[82] = {
    Type = "Normal",
    DocTag = "NGPlus-revisit@v1#1",
    NpcName = "淑芬",
    NpcSprite = "团聚",
    Dialogue = "孩儿在身边了。谢谢你。",
    Next = 83  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus-revisit@v1#2
-- Position: { 9600, 1450 }
DialogueConfig[83] = {
    Type = "Normal",
    DocTag = "NGPlus-revisit@v1#2",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "淑芬，那只乌鸦叼的原来是石头。",
    Next = 84  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus-revisit@v1#3
-- Position: { 9950, 1450 }
DialogueConfig[84] = {
    Type = "Normal",
    DocTag = "NGPlus-revisit@v1#3",
    NpcName = "淑芬",
    NpcSprite = "团聚",
    Dialogue = "……闹成这样了。",
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus-revisit@v2#1
-- Position: { 9250, 1730 }
DialogueConfig[85] = {
    Type = "Normal",
    DocTag = "NGPlus-revisit@v2#1",
    NpcName = "淑芬",
    NpcSprite = "团聚",
    Dialogue = "主人那两脚兽……我以后也不赶他了。",
    Next = 86  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus-revisit@v2#2
-- Position: { 9600, 1730 }
DialogueConfig[86] = {
    Type = "Normal",
    DocTag = "NGPlus-revisit@v2#2",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "嗯。",
    Next = 87  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus-revisit@v2#3
-- Position: { 9950, 1730 }
DialogueConfig[87] = {
    Type = "Normal",
    DocTag = "NGPlus-revisit@v2#3",
    NpcName = "淑芬",
    NpcSprite = "团聚",
    Dialogue = "呃……偶尔还是赶一下。",
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus-revisit
-- Position: { 9250, 2010 }
DialogueConfig[88] = {
    Type = "Normal",
    DocTag = "NGPlus-revisit",
    NpcName = "淑芬",
    NpcSprite = "团聚",
    Dialogue = "",
    RotatePool = { 82, 85 },
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:entry#comm
-- Position: { 750, 150 }
DialogueConfig[89] = {
    Type = "Normal",
    DocTag = "entry#comm",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "Shufen_CommissionDone", VarType = "bool", TrueNext = 23, FalseNext = -1 }
    },
    Next = -1  -- 下一段对话ID
}

-- 普通对话类型  -- doc:entry#new
-- Position: { 400, 150 }
DialogueConfig[90] = {
    Type = "Normal",
    DocTag = "entry#new",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "Shufen_CommissionDone", VarType = "bool", TrueNext = 89, FalseNext = 1 }
    },
    Next = 89  -- 下一段对话ID
}

-- 普通对话类型  -- doc:NGPlus#1
DialogueConfig[91] = {
    Type = "Normal",
    DocTag = "NGPlus#1",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（淑芬蹲在窝边；一只刚出壳的小鸡正往她翅膀下拱）",
    Next = 92
}

DialogueConfig[92] = {
    Type = "Normal",
    DocTag = "NGPlus#2",
    NpcName = "淑芬",
    NpcSprite = "团聚",
    Dialogue = "……你来了。",
    Next = 93
}

DialogueConfig[93] = {
    Type = "Normal",
    DocTag = "NGPlus#3",
    NpcName = "淑芬",
    NpcSprite = "团聚",
    Dialogue = "你都不敢相信——他居然自己回来了。",
    Next = 94
}

DialogueConfig[94] = {
    Type = "Normal",
    DocTag = "NGPlus#4",
    NpcName = "玩家",
    NpcSprite = "疑惑",
    Dialogue = "他自己回来的？",
    Next = 95
}

DialogueConfig[95] = {
    Type = "Normal",
    DocTag = "NGPlus#5",
    NpcName = "淑芬",
    NpcSprite = "团聚",
    Dialogue = "嗯。已经破壳了。小小一只。",
    Next = 96
}

DialogueConfig[96] = {
    Type = "Normal",
    DocTag = "NGPlus#6",
    NpcName = "淑芬",
    NpcSprite = "团聚",
    Dialogue = "自己走进来的。站在门口叫我。",
    Next = 97
}

DialogueConfig[97] = {
    Type = "Normal",
    DocTag = "NGPlus#7",
    NpcName = "描述",
    NpcSprite = "",
    Dialogue = "（翅膀把小鸡拢了拢）",
    Next = 98
}

DialogueConfig[98] = {
    Type = "Normal",
    DocTag = "NGPlus#8",
    NpcName = "淑芬",
    NpcSprite = "团聚",
    Dialogue = "窝空了那么久，我以为……",
    Next = 99
}

DialogueConfig[99] = {
    Type = "Normal",
    DocTag = "NGPlus#9",
    NpcName = "玩家",
    NpcSprite = "",
    Dialogue = "那就好。",
    Next = 100
}

DialogueConfig[100] = {
    Type = "Normal",
    DocTag = "NGPlus#10",
    NpcName = "淑芬",
    NpcSprite = "团聚",
    Dialogue = "……谢谢你。真的。",
    Next = 101
}

DialogueConfig[101] = {
    Type = "Normal",
    DocTag = "NGPlus#11",
    NpcName = "淑芬",
    NpcSprite = "团聚",
    Dialogue = "要不是你满院子跑，我不知道该怎么办。",
    SetVariables = {
        { VarName = "Shufen_NGPlusShown", VarType = "bool", Value = true }
    },
    Next = -1
}

-- 普通对话类型  -- doc:entry#ng1
DialogueConfig[103] = {
    Type = "Normal",
    DocTag = "entry#ng1",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "Shufen_NGPlusShown", VarType = "bool", TrueNext = 90, FalseNext = 91 }
    },
    Next = 91
}

-- 普通对话类型  -- doc:entry#ng2
DialogueConfig[104] = {
    Type = "Normal",
    DocTag = "entry#ng2",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "Shufen_NGPlusShown", VarType = "bool", TrueNext = 88, FalseNext = 103 }
    },
    Next = 103
}

-- 普通对话类型  -- doc:entry#0
-- Position: { 50, 150 }
DialogueConfig[0] = {
    Type = "Normal",
    DocTag = "entry#0",
    NpcName = "淑芬",
    NpcSprite = "护雏",
    Dialogue = "",
    ConditionBranches = {
        { VarName = "NGPlus", VarType = "bool", TrueNext = 104, FalseNext = 90 }
    },
    Next = 90  -- 下一段对话ID
}
