-- 对话配置文件
-- Generated by doc_to_lua.py (Phase 2 — do not overwrite production files)
-- Scene DialogueTrigger start ID should be 1（1-A 首节点，无 entry）
-- doc node map:
--   1-A -> DialogueConfig[1]

DialogueConfig = {}

-- 普通对话类型  -- doc:1-A#1
-- Position: { 50, 150 }
DialogueConfig[1] = {
    Type = "Normal",
    DocTag = "1-A#1",
    NpcName = "豆豆",
    NpcSprite = "背对",
    Dialogue = "（压声）昨晚外面那声音……肯定是水怪干的……",
    Next = 2  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-A#2
-- Position: { 400, 150 }
DialogueConfig[2] = {
    Type = "Normal",
    DocTag = "1-A#2",
    NpcName = "米粒",
    NpcSprite = "背对",
    Dialogue = "（压声）池塘那边青蛙还说，宝珠沉下去了……",
    Next = 3  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-A#3
-- Position: { 750, 150 }
DialogueConfig[3] = {
    Type = "Normal",
    DocTag = "1-A#3",
    NpcName = "瓜子",
    NpcSprite = "背对",
    Dialogue = "（极小声）……可是大前天……明明是我们自己……",
    Next = 4  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-A#4
-- Position: { 1100, 150 }
DialogueConfig[4] = {
    Type = "Normal",
    DocTag = "1-A#4",
    NpcName = "阿满",
    NpcSprite = "背对",
    Dialogue = "（压声）瓜子！别说了！",
    Next = 5  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-A#5
-- Position: { 1450, 150 }
DialogueConfig[5] = {
    Type = "Normal",
    DocTag = "1-A#5",
    NpcName = "豆豆",
    NpcSprite = "背对",
    Dialogue = "（压声）那要是有人来问，咱们怎么说？",
    Next = 6  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-A#6
-- Position: { 1800, 150 }
DialogueConfig[6] = {
    Type = "Normal",
    DocTag = "1-A#6",
    NpcName = "阿满",
    NpcSprite = "背对",
    Dialogue = "（压声）就说……水怪。从池塘来的。把蛋叼走了……",
    Next = 7  -- 下一段对话ID
}

-- 普通对话类型  -- doc:1-A#7
-- Position: { 2150, 150 }
DialogueConfig[7] = {
    Type = "Normal",
    DocTag = "1-A#7",
    NpcName = "阿满",
    NpcSprite = "背对",
    Dialogue = "（压声）只能是这样……不然弟弟怎么会不见……",
    SetVariables = {
        { VarName = "E03_Overheard", VarType = "bool", Value = true }
    },
    Next = -1  -- 下一段对话ID
}